/* This file is automatically generated. */
/* The content of this header file is a derived work of corresponding CUDA header files, */
/* and will need to comply NVIDIA CUDA SDK EULA. */


/*
 * Copyright 1993-2018 NVIDIA Corporation.  All rights reserved.
 *
 * NOTICE TO LICENSEE:
 *
 * This source code and/or documentation ("Licensed Deliverables") are
 * subject to NVIDIA intellectual property rights under U.S. and
 * international Copyright laws.
 *
 * These Licensed Deliverables contained herein is PROPRIETARY and
 * CONFIDENTIAL to NVIDIA and is being provided under the terms and
 * conditions of a form of NVIDIA software license agreement by and
 * between NVIDIA and Licensee ("License Agreement") or electronically
 * accepted by Licensee.  Notwithstanding any terms or conditions to
 * the contrary in the License Agreement, reproduction or disclosure
 * of the Licensed Deliverables to any third party without the express
 * written consent of NVIDIA is prohibited.
 *
 * NOTWITHSTANDING ANY TERMS OR CONDITIONS TO THE CONTRARY IN THE
 * LICENSE AGREEMENT, NVIDIA MAKES NO REPRESENTATION ABOUT THE
 * SUITABILITY OF THESE LICENSED DELIVERABLES FOR ANY PURPOSE.  IT IS
 * PROVIDED "AS IS" WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND.
 * NVIDIA DISCLAIMS ALL WARRANTIES WITH REGARD TO THESE LICENSED
 * DELIVERABLES, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY,
 * NONINFRINGEMENT, AND FITNESS FOR A PARTICULAR PURPOSE.
 * NOTWITHSTANDING ANY TERMS OR CONDITIONS TO THE CONTRARY IN THE
 * LICENSE AGREEMENT, IN NO EVENT SHALL NVIDIA BE LIABLE FOR ANY
 * SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, OR ANY
 * DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS
 * ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
 * OF THESE LICENSED DELIVERABLES.
 *
 * U.S. Government End Users.  These Licensed Deliverables are a
 * "commercial item" as that term is defined at 48 C.F.R. 2.101 (OCT
 * 1995), consisting of "commercial computer software" and "commercial
 * computer software documentation" as such terms are used in 48
 * C.F.R. 12.212 (SEPT 1995) and is provided to the U.S. Government
 * only as a commercial end item.  Consistent with 48 C.F.R.12.212 and
 * 48 C.F.R. 227.7202-1 through 227.7202-4 (JUNE 1995), all
 * U.S. Government End Users acquire the Licensed Deliverables with
 * only those rights set forth herein.
 *
 * Any use of the Licensed Deliverables in individual and commercial
 * software must include, in the user documentation and internal
 * comments to the code, the above Disclaimer and U.S. Government End
 * Users Notice.
 */
#ifndef CUEW_CUBLAS_H_
#define CUEW_CUBLAS_H_

#include <stdint.h>


#include <stddef.h>


#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif


#ifndef CUDAAPI
#ifdef _WIN32
#  define CUDAAPI __stdcall
#  define CUDA_CB __stdcall
#else
#  define CUDAAPI
#  define CUDA_CB
#endif
#endif

/*struct cudaChannelFormatDesc; */

#ifdef __clang__
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-id-macro"
#pragma clang diagnostic ignored "-Wpadded"
#if __has_warning("-Wdocumentation-deprecated-sync")
  #pragma clang diagnostic ignored "-Wdocumentation-deprecated-sync"
#endif
#endif
#include "cuew_cudart.h"
#include "cuComplex.h"
#ifdef __clang__
#pragma clang diagnostic pop
#endif
typedef enum 
{
  CUBLAS_STATUS_SUCCESS = 0,
  CUBLAS_STATUS_NOT_INITIALIZED = 1,
  CUBLAS_STATUS_ALLOC_FAILED = 3,
  CUBLAS_STATUS_INVALID_VALUE = 7,
  CUBLAS_STATUS_ARCH_MISMATCH = 8,
  CUBLAS_STATUS_MAPPING_ERROR = 11,
  CUBLAS_STATUS_EXECUTION_FAILED = 13,
  CUBLAS_STATUS_INTERNAL_ERROR = 14,
  CUBLAS_STATUS_NOT_SUPPORTED = 15,
  CUBLAS_STATUS_LICENSE_ERROR = 16
} cublasStatus_t; // id 0xfd12b8 

typedef enum 
{
  CUBLAS_FILL_MODE_LOWER = 0,
  CUBLAS_FILL_MODE_UPPER = 1,
  CUBLAS_FILL_MODE_FULL = 2
} cublasFillMode_t; // id 0xfd1998 

typedef enum 
{
  CUBLAS_DIAG_NON_UNIT = 0,
  CUBLAS_DIAG_UNIT = 1
} cublasDiagType_t; // id 0xfd1cc8 

typedef enum 
{
  CUBLAS_SIDE_LEFT = 0,
  CUBLAS_SIDE_RIGHT = 1
} cublasSideMode_t; // id 0xfd1f68 

typedef enum 
{
  CUBLAS_OP_N = 0,
  CUBLAS_OP_T = 1,
  CUBLAS_OP_C = 2,
  CUBLAS_OP_HERMITAN = 2,
  CUBLAS_OP_CONJG = 3
} cublasOperation_t; // id 0xfd2208 

typedef enum 
{
  CUBLAS_POINTER_MODE_HOST = 0,
  CUBLAS_POINTER_MODE_DEVICE = 1
} cublasPointerMode_t; // id 0xfd2648 

typedef enum 
{
  CUBLAS_ATOMICS_NOT_ALLOWED = 0,
  CUBLAS_ATOMICS_ALLOWED = 1
} cublasAtomicsMode_t; // id 0xfd28e8 

typedef enum 
{
  CUBLAS_GEMM_DFALT = -1,
  CUBLAS_GEMM_DEFAULT = -1,
  CUBLAS_GEMM_ALGO0 = 0,
  CUBLAS_GEMM_ALGO1 = 1,
  CUBLAS_GEMM_ALGO2 = 2,
  CUBLAS_GEMM_ALGO3 = 3,
  CUBLAS_GEMM_ALGO4 = 4,
  CUBLAS_GEMM_ALGO5 = 5,
  CUBLAS_GEMM_ALGO6 = 6,
  CUBLAS_GEMM_ALGO7 = 7,
  CUBLAS_GEMM_ALGO8 = 8,
  CUBLAS_GEMM_ALGO9 = 9,
  CUBLAS_GEMM_ALGO10 = 10,
  CUBLAS_GEMM_ALGO11 = 11,
  CUBLAS_GEMM_ALGO12 = 12,
  CUBLAS_GEMM_ALGO13 = 13,
  CUBLAS_GEMM_ALGO14 = 14,
  CUBLAS_GEMM_ALGO15 = 15,
  CUBLAS_GEMM_ALGO16 = 16,
  CUBLAS_GEMM_ALGO17 = 17,
  CUBLAS_GEMM_ALGO18 = 18,
  CUBLAS_GEMM_ALGO19 = 19,
  CUBLAS_GEMM_ALGO20 = 20,
  CUBLAS_GEMM_ALGO21 = 21,
  CUBLAS_GEMM_ALGO22 = 22,
  CUBLAS_GEMM_ALGO23 = 23,
  CUBLAS_GEMM_DEFAULT_TENSOR_OP = 99,
  CUBLAS_GEMM_DFALT_TENSOR_OP = 99,
  CUBLAS_GEMM_ALGO0_TENSOR_OP = 100,
  CUBLAS_GEMM_ALGO1_TENSOR_OP = 101,
  CUBLAS_GEMM_ALGO2_TENSOR_OP = 102,
  CUBLAS_GEMM_ALGO3_TENSOR_OP = 103,
  CUBLAS_GEMM_ALGO4_TENSOR_OP = 104,
  CUBLAS_GEMM_ALGO5_TENSOR_OP = 105,
  CUBLAS_GEMM_ALGO6_TENSOR_OP = 106,
  CUBLAS_GEMM_ALGO7_TENSOR_OP = 107,
  CUBLAS_GEMM_ALGO8_TENSOR_OP = 108,
  CUBLAS_GEMM_ALGO9_TENSOR_OP = 109,
  CUBLAS_GEMM_ALGO10_TENSOR_OP = 110,
  CUBLAS_GEMM_ALGO11_TENSOR_OP = 111,
  CUBLAS_GEMM_ALGO12_TENSOR_OP = 112,
  CUBLAS_GEMM_ALGO13_TENSOR_OP = 113,
  CUBLAS_GEMM_ALGO14_TENSOR_OP = 114,
  CUBLAS_GEMM_ALGO15_TENSOR_OP = 115
} cublasGemmAlgo_t; // id 0xfd2b88 

typedef enum 
{
  CUBLAS_DEFAULT_MATH = 0,
  CUBLAS_TENSOR_OP_MATH = 1,
  CUBLAS_PEDANTIC_MATH = 2,
  CUBLAS_TF32_TENSOR_OP_MATH = 3,
  CUBLAS_MATH_DISALLOW_REDUCED_PRECISION_REDUCTION = 16
} cublasMath_t; // id 0xfd44f8 

typedef enum 
{
  CUBLAS_COMPUTE_16F = 64,
  CUBLAS_COMPUTE_16F_PEDANTIC = 65,
  CUBLAS_COMPUTE_32F = 68,
  CUBLAS_COMPUTE_32F_PEDANTIC = 69,
  CUBLAS_COMPUTE_32F_FAST_16F = 74,
  CUBLAS_COMPUTE_32F_FAST_16BF = 75,
  CUBLAS_COMPUTE_32F_FAST_TF32 = 77,
  CUBLAS_COMPUTE_64F = 70,
  CUBLAS_COMPUTE_64F_PEDANTIC = 71,
  CUBLAS_COMPUTE_32I = 72,
  CUBLAS_COMPUTE_32I_PEDANTIC = 73
} cublasComputeType_t; // id 0xfd49c8 

struct cublasContext;
typedef struct cublasContext * cublasHandle_t; // id 0xfd62c0 

typedef cublasStatus_t  CUDAAPI tcublasCreate_v2(cublasHandle_t *);
extern tcublasCreate_v2 *cublasCreate_v2;
typedef cublasStatus_t  CUDAAPI tcublasDestroy_v2(cublasHandle_t);
extern tcublasDestroy_v2 *cublasDestroy_v2;
typedef cublasStatus_t  CUDAAPI tcublasGetVersion_v2(cublasHandle_t, int *);
extern tcublasGetVersion_v2 *cublasGetVersion_v2;
typedef cublasStatus_t  CUDAAPI tcublasGetProperty(libraryPropertyType, int *);
extern tcublasGetProperty *cublasGetProperty;
typedef size_t  CUDAAPI tcublasGetCudartVersion(void);
extern tcublasGetCudartVersion *cublasGetCudartVersion;
typedef cublasStatus_t  CUDAAPI tcublasSetWorkspace_v2(cublasHandle_t, void *, size_t);
extern tcublasSetWorkspace_v2 *cublasSetWorkspace_v2;
typedef cublasStatus_t  CUDAAPI tcublasSetStream_v2(cublasHandle_t, cudaStream_t);
extern tcublasSetStream_v2 *cublasSetStream_v2;
typedef cublasStatus_t  CUDAAPI tcublasGetStream_v2(cublasHandle_t, cudaStream_t *);
extern tcublasGetStream_v2 *cublasGetStream_v2;
typedef cublasStatus_t  CUDAAPI tcublasGetPointerMode_v2(cublasHandle_t, cublasPointerMode_t *);
extern tcublasGetPointerMode_v2 *cublasGetPointerMode_v2;
typedef cublasStatus_t  CUDAAPI tcublasSetPointerMode_v2(cublasHandle_t, cublasPointerMode_t);
extern tcublasSetPointerMode_v2 *cublasSetPointerMode_v2;
typedef cublasStatus_t  CUDAAPI tcublasGetAtomicsMode(cublasHandle_t, cublasAtomicsMode_t *);
extern tcublasGetAtomicsMode *cublasGetAtomicsMode;
typedef cublasStatus_t  CUDAAPI tcublasSetAtomicsMode(cublasHandle_t, cublasAtomicsMode_t);
extern tcublasSetAtomicsMode *cublasSetAtomicsMode;
typedef cublasStatus_t  CUDAAPI tcublasGetMathMode(cublasHandle_t, cublasMath_t *);
extern tcublasGetMathMode *cublasGetMathMode;
typedef cublasStatus_t  CUDAAPI tcublasSetMathMode(cublasHandle_t, cublasMath_t);
extern tcublasSetMathMode *cublasSetMathMode;
typedef cublasStatus_t  CUDAAPI tcublasGetSmCountTarget(cublasHandle_t, int *);
extern tcublasGetSmCountTarget *cublasGetSmCountTarget;
typedef cublasStatus_t  CUDAAPI tcublasSetSmCountTarget(cublasHandle_t, int);
extern tcublasSetSmCountTarget *cublasSetSmCountTarget;
typedef const char * CUDAAPI tcublasGetStatusName(cublasStatus_t);
extern tcublasGetStatusName *cublasGetStatusName;
typedef const char * CUDAAPI tcublasGetStatusString(cublasStatus_t);
extern tcublasGetStatusString *cublasGetStatusString;
typedef void (*cublasLogCallback)(const char *); // id 0xfd9d70 

typedef cublasStatus_t  CUDAAPI tcublasLoggerConfigure(int, int, int, const char *);
extern tcublasLoggerConfigure *cublasLoggerConfigure;
typedef cublasStatus_t  CUDAAPI tcublasSetLoggerCallback(cublasLogCallback);
extern tcublasSetLoggerCallback *cublasSetLoggerCallback;
typedef cublasStatus_t  CUDAAPI tcublasGetLoggerCallback(cublasLogCallback *);
extern tcublasGetLoggerCallback *cublasGetLoggerCallback;
typedef cublasStatus_t  CUDAAPI tcublasSetVector(int, int, const void *, int, void *, int);
extern tcublasSetVector *cublasSetVector;
typedef cublasStatus_t  CUDAAPI tcublasGetVector(int, int, const void *, int, void *, int);
extern tcublasGetVector *cublasGetVector;
typedef cublasStatus_t  CUDAAPI tcublasSetMatrix(int, int, int, const void *, int, void *, int);
extern tcublasSetMatrix *cublasSetMatrix;
typedef cublasStatus_t  CUDAAPI tcublasGetMatrix(int, int, int, const void *, int, void *, int);
extern tcublasGetMatrix *cublasGetMatrix;
typedef cublasStatus_t  CUDAAPI tcublasSetVectorAsync(int, int, const void *, int, void *, int, cudaStream_t);
extern tcublasSetVectorAsync *cublasSetVectorAsync;
typedef cublasStatus_t  CUDAAPI tcublasGetVectorAsync(int, int, const void *, int, void *, int, cudaStream_t);
extern tcublasGetVectorAsync *cublasGetVectorAsync;
typedef cublasStatus_t  CUDAAPI tcublasSetMatrixAsync(int, int, int, const void *, int, void *, int, cudaStream_t);
extern tcublasSetMatrixAsync *cublasSetMatrixAsync;
typedef cublasStatus_t  CUDAAPI tcublasGetMatrixAsync(int, int, int, const void *, int, void *, int, cudaStream_t);
extern tcublasGetMatrixAsync *cublasGetMatrixAsync;
typedef void  CUDAAPI tcublasXerbla(const char *, int);
extern tcublasXerbla *cublasXerbla;
typedef cublasStatus_t  CUDAAPI tcublasNrm2Ex(cublasHandle_t, int, const void *, cudaDataType, int, void *, cudaDataType, cudaDataType);
extern tcublasNrm2Ex *cublasNrm2Ex;
typedef cublasStatus_t  CUDAAPI tcublasSnrm2_v2(cublasHandle_t, int, const float *, int, float *);
extern tcublasSnrm2_v2 *cublasSnrm2_v2;
typedef cublasStatus_t  CUDAAPI tcublasDnrm2_v2(cublasHandle_t, int, const double *, int, double *);
extern tcublasDnrm2_v2 *cublasDnrm2_v2;
typedef cublasStatus_t  CUDAAPI tcublasScnrm2_v2(cublasHandle_t, int, const cuComplex *, int, float *);
extern tcublasScnrm2_v2 *cublasScnrm2_v2;
typedef cublasStatus_t  CUDAAPI tcublasDznrm2_v2(cublasHandle_t, int, const cuDoubleComplex *, int, double *);
extern tcublasDznrm2_v2 *cublasDznrm2_v2;
typedef cublasStatus_t  CUDAAPI tcublasDotEx(cublasHandle_t, int, const void *, cudaDataType, int, const void *, cudaDataType, int, void *, cudaDataType, cudaDataType);
extern tcublasDotEx *cublasDotEx;
typedef cublasStatus_t  CUDAAPI tcublasDotcEx(cublasHandle_t, int, const void *, cudaDataType, int, const void *, cudaDataType, int, void *, cudaDataType, cudaDataType);
extern tcublasDotcEx *cublasDotcEx;
typedef cublasStatus_t  CUDAAPI tcublasSdot_v2(cublasHandle_t, int, const float *, int, const float *, int, float *);
extern tcublasSdot_v2 *cublasSdot_v2;
typedef cublasStatus_t  CUDAAPI tcublasDdot_v2(cublasHandle_t, int, const double *, int, const double *, int, double *);
extern tcublasDdot_v2 *cublasDdot_v2;
typedef cublasStatus_t  CUDAAPI tcublasCdotu_v2(cublasHandle_t, int, const cuComplex *, int, const cuComplex *, int, cuComplex *);
extern tcublasCdotu_v2 *cublasCdotu_v2;
typedef cublasStatus_t  CUDAAPI tcublasCdotc_v2(cublasHandle_t, int, const cuComplex *, int, const cuComplex *, int, cuComplex *);
extern tcublasCdotc_v2 *cublasCdotc_v2;
typedef cublasStatus_t  CUDAAPI tcublasZdotu_v2(cublasHandle_t, int, const cuDoubleComplex *, int, const cuDoubleComplex *, int, cuDoubleComplex *);
extern tcublasZdotu_v2 *cublasZdotu_v2;
typedef cublasStatus_t  CUDAAPI tcublasZdotc_v2(cublasHandle_t, int, const cuDoubleComplex *, int, const cuDoubleComplex *, int, cuDoubleComplex *);
extern tcublasZdotc_v2 *cublasZdotc_v2;
typedef cublasStatus_t  CUDAAPI tcublasScalEx(cublasHandle_t, int, const void *, cudaDataType, void *, cudaDataType, int, cudaDataType);
extern tcublasScalEx *cublasScalEx;
typedef cublasStatus_t  CUDAAPI tcublasSscal_v2(cublasHandle_t, int, const float *, float *, int);
extern tcublasSscal_v2 *cublasSscal_v2;
typedef cublasStatus_t  CUDAAPI tcublasDscal_v2(cublasHandle_t, int, const double *, double *, int);
extern tcublasDscal_v2 *cublasDscal_v2;
typedef cublasStatus_t  CUDAAPI tcublasCscal_v2(cublasHandle_t, int, const cuComplex *, cuComplex *, int);
extern tcublasCscal_v2 *cublasCscal_v2;
typedef cublasStatus_t  CUDAAPI tcublasCsscal_v2(cublasHandle_t, int, const float *, cuComplex *, int);
extern tcublasCsscal_v2 *cublasCsscal_v2;
typedef cublasStatus_t  CUDAAPI tcublasZscal_v2(cublasHandle_t, int, const cuDoubleComplex *, cuDoubleComplex *, int);
extern tcublasZscal_v2 *cublasZscal_v2;
typedef cublasStatus_t  CUDAAPI tcublasZdscal_v2(cublasHandle_t, int, const double *, cuDoubleComplex *, int);
extern tcublasZdscal_v2 *cublasZdscal_v2;
typedef cublasStatus_t  CUDAAPI tcublasAxpyEx(cublasHandle_t, int, const void *, cudaDataType, const void *, cudaDataType, int, void *, cudaDataType, int, cudaDataType);
extern tcublasAxpyEx *cublasAxpyEx;
typedef cublasStatus_t  CUDAAPI tcublasSaxpy_v2(cublasHandle_t, int, const float *, const float *, int, float *, int);
extern tcublasSaxpy_v2 *cublasSaxpy_v2;
typedef cublasStatus_t  CUDAAPI tcublasDaxpy_v2(cublasHandle_t, int, const double *, const double *, int, double *, int);
extern tcublasDaxpy_v2 *cublasDaxpy_v2;
typedef cublasStatus_t  CUDAAPI tcublasCaxpy_v2(cublasHandle_t, int, const cuComplex *, const cuComplex *, int, cuComplex *, int);
extern tcublasCaxpy_v2 *cublasCaxpy_v2;
typedef cublasStatus_t  CUDAAPI tcublasZaxpy_v2(cublasHandle_t, int, const cuDoubleComplex *, const cuDoubleComplex *, int, cuDoubleComplex *, int);
extern tcublasZaxpy_v2 *cublasZaxpy_v2;
typedef cublasStatus_t  CUDAAPI tcublasCopyEx(cublasHandle_t, int, const void *, cudaDataType, int, void *, cudaDataType, int);
extern tcublasCopyEx *cublasCopyEx;
typedef cublasStatus_t  CUDAAPI tcublasScopy_v2(cublasHandle_t, int, const float *, int, float *, int);
extern tcublasScopy_v2 *cublasScopy_v2;
typedef cublasStatus_t  CUDAAPI tcublasDcopy_v2(cublasHandle_t, int, const double *, int, double *, int);
extern tcublasDcopy_v2 *cublasDcopy_v2;
typedef cublasStatus_t  CUDAAPI tcublasCcopy_v2(cublasHandle_t, int, const cuComplex *, int, cuComplex *, int);
extern tcublasCcopy_v2 *cublasCcopy_v2;
typedef cublasStatus_t  CUDAAPI tcublasZcopy_v2(cublasHandle_t, int, const cuDoubleComplex *, int, cuDoubleComplex *, int);
extern tcublasZcopy_v2 *cublasZcopy_v2;
typedef cublasStatus_t  CUDAAPI tcublasSswap_v2(cublasHandle_t, int, float *, int, float *, int);
extern tcublasSswap_v2 *cublasSswap_v2;
typedef cublasStatus_t  CUDAAPI tcublasDswap_v2(cublasHandle_t, int, double *, int, double *, int);
extern tcublasDswap_v2 *cublasDswap_v2;
typedef cublasStatus_t  CUDAAPI tcublasCswap_v2(cublasHandle_t, int, cuComplex *, int, cuComplex *, int);
extern tcublasCswap_v2 *cublasCswap_v2;
typedef cublasStatus_t  CUDAAPI tcublasZswap_v2(cublasHandle_t, int, cuDoubleComplex *, int, cuDoubleComplex *, int);
extern tcublasZswap_v2 *cublasZswap_v2;
typedef cublasStatus_t  CUDAAPI tcublasSwapEx(cublasHandle_t, int, void *, cudaDataType, int, void *, cudaDataType, int);
extern tcublasSwapEx *cublasSwapEx;
typedef cublasStatus_t  CUDAAPI tcublasIsamax_v2(cublasHandle_t, int, const float *, int, int *);
extern tcublasIsamax_v2 *cublasIsamax_v2;
typedef cublasStatus_t  CUDAAPI tcublasIdamax_v2(cublasHandle_t, int, const double *, int, int *);
extern tcublasIdamax_v2 *cublasIdamax_v2;
typedef cublasStatus_t  CUDAAPI tcublasIcamax_v2(cublasHandle_t, int, const cuComplex *, int, int *);
extern tcublasIcamax_v2 *cublasIcamax_v2;
typedef cublasStatus_t  CUDAAPI tcublasIzamax_v2(cublasHandle_t, int, const cuDoubleComplex *, int, int *);
extern tcublasIzamax_v2 *cublasIzamax_v2;
typedef cublasStatus_t  CUDAAPI tcublasIamaxEx(cublasHandle_t, int, const void *, cudaDataType, int, int *);
extern tcublasIamaxEx *cublasIamaxEx;
typedef cublasStatus_t  CUDAAPI tcublasIsamin_v2(cublasHandle_t, int, const float *, int, int *);
extern tcublasIsamin_v2 *cublasIsamin_v2;
typedef cublasStatus_t  CUDAAPI tcublasIdamin_v2(cublasHandle_t, int, const double *, int, int *);
extern tcublasIdamin_v2 *cublasIdamin_v2;
typedef cublasStatus_t  CUDAAPI tcublasIcamin_v2(cublasHandle_t, int, const cuComplex *, int, int *);
extern tcublasIcamin_v2 *cublasIcamin_v2;
typedef cublasStatus_t  CUDAAPI tcublasIzamin_v2(cublasHandle_t, int, const cuDoubleComplex *, int, int *);
extern tcublasIzamin_v2 *cublasIzamin_v2;
typedef cublasStatus_t  CUDAAPI tcublasIaminEx(cublasHandle_t, int, const void *, cudaDataType, int, int *);
extern tcublasIaminEx *cublasIaminEx;
typedef cublasStatus_t  CUDAAPI tcublasAsumEx(cublasHandle_t, int, const void *, cudaDataType, int, void *, cudaDataType, cudaDataType);
extern tcublasAsumEx *cublasAsumEx;
typedef cublasStatus_t  CUDAAPI tcublasSasum_v2(cublasHandle_t, int, const float *, int, float *);
extern tcublasSasum_v2 *cublasSasum_v2;
typedef cublasStatus_t  CUDAAPI tcublasDasum_v2(cublasHandle_t, int, const double *, int, double *);
extern tcublasDasum_v2 *cublasDasum_v2;
typedef cublasStatus_t  CUDAAPI tcublasScasum_v2(cublasHandle_t, int, const cuComplex *, int, float *);
extern tcublasScasum_v2 *cublasScasum_v2;
typedef cublasStatus_t  CUDAAPI tcublasDzasum_v2(cublasHandle_t, int, const cuDoubleComplex *, int, double *);
extern tcublasDzasum_v2 *cublasDzasum_v2;
typedef cublasStatus_t  CUDAAPI tcublasSrot_v2(cublasHandle_t, int, float *, int, float *, int, const float *, const float *);
extern tcublasSrot_v2 *cublasSrot_v2;
typedef cublasStatus_t  CUDAAPI tcublasDrot_v2(cublasHandle_t, int, double *, int, double *, int, const double *, const double *);
extern tcublasDrot_v2 *cublasDrot_v2;
typedef cublasStatus_t  CUDAAPI tcublasCrot_v2(cublasHandle_t, int, cuComplex *, int, cuComplex *, int, const float *, const cuComplex *);
extern tcublasCrot_v2 *cublasCrot_v2;
typedef cublasStatus_t  CUDAAPI tcublasCsrot_v2(cublasHandle_t, int, cuComplex *, int, cuComplex *, int, const float *, const float *);
extern tcublasCsrot_v2 *cublasCsrot_v2;
typedef cublasStatus_t  CUDAAPI tcublasZrot_v2(cublasHandle_t, int, cuDoubleComplex *, int, cuDoubleComplex *, int, const double *, const cuDoubleComplex *);
extern tcublasZrot_v2 *cublasZrot_v2;
typedef cublasStatus_t  CUDAAPI tcublasZdrot_v2(cublasHandle_t, int, cuDoubleComplex *, int, cuDoubleComplex *, int, const double *, const double *);
extern tcublasZdrot_v2 *cublasZdrot_v2;
typedef cublasStatus_t  CUDAAPI tcublasRotEx(cublasHandle_t, int, void *, cudaDataType, int, void *, cudaDataType, int, const void *, const void *, cudaDataType, cudaDataType);
extern tcublasRotEx *cublasRotEx;
typedef cublasStatus_t  CUDAAPI tcublasSrotg_v2(cublasHandle_t, float *, float *, float *, float *);
extern tcublasSrotg_v2 *cublasSrotg_v2;
typedef cublasStatus_t  CUDAAPI tcublasDrotg_v2(cublasHandle_t, double *, double *, double *, double *);
extern tcublasDrotg_v2 *cublasDrotg_v2;
typedef cublasStatus_t  CUDAAPI tcublasCrotg_v2(cublasHandle_t, cuComplex *, cuComplex *, float *, cuComplex *);
extern tcublasCrotg_v2 *cublasCrotg_v2;
typedef cublasStatus_t  CUDAAPI tcublasZrotg_v2(cublasHandle_t, cuDoubleComplex *, cuDoubleComplex *, double *, cuDoubleComplex *);
extern tcublasZrotg_v2 *cublasZrotg_v2;
typedef cublasStatus_t  CUDAAPI tcublasRotgEx(cublasHandle_t, void *, void *, cudaDataType, void *, void *, cudaDataType, cudaDataType);
extern tcublasRotgEx *cublasRotgEx;
typedef cublasStatus_t  CUDAAPI tcublasSrotm_v2(cublasHandle_t, int, float *, int, float *, int, const float *);
extern tcublasSrotm_v2 *cublasSrotm_v2;
typedef cublasStatus_t  CUDAAPI tcublasDrotm_v2(cublasHandle_t, int, double *, int, double *, int, const double *);
extern tcublasDrotm_v2 *cublasDrotm_v2;
typedef cublasStatus_t  CUDAAPI tcublasRotmEx(cublasHandle_t, int, void *, cudaDataType, int, void *, cudaDataType, int, const void *, cudaDataType, cudaDataType);
extern tcublasRotmEx *cublasRotmEx;
typedef cublasStatus_t  CUDAAPI tcublasSrotmg_v2(cublasHandle_t, float *, float *, float *, const float *, float *);
extern tcublasSrotmg_v2 *cublasSrotmg_v2;
typedef cublasStatus_t  CUDAAPI tcublasDrotmg_v2(cublasHandle_t, double *, double *, double *, const double *, double *);
extern tcublasDrotmg_v2 *cublasDrotmg_v2;
typedef cublasStatus_t  CUDAAPI tcublasRotmgEx(cublasHandle_t, void *, cudaDataType, void *, cudaDataType, void *, cudaDataType, const void *, cudaDataType, void *, cudaDataType, cudaDataType);
extern tcublasRotmgEx *cublasRotmgEx;
typedef cublasStatus_t  CUDAAPI tcublasSgemv_v2(cublasHandle_t, cublasOperation_t, int, int, const float *, const float *, int, const float *, int, const float *, float *, int);
extern tcublasSgemv_v2 *cublasSgemv_v2;
typedef cublasStatus_t  CUDAAPI tcublasDgemv_v2(cublasHandle_t, cublasOperation_t, int, int, const double *, const double *, int, const double *, int, const double *, double *, int);
extern tcublasDgemv_v2 *cublasDgemv_v2;
typedef cublasStatus_t  CUDAAPI tcublasCgemv_v2(cublasHandle_t, cublasOperation_t, int, int, const cuComplex *, const cuComplex *, int, const cuComplex *, int, const cuComplex *, cuComplex *, int);
extern tcublasCgemv_v2 *cublasCgemv_v2;
typedef cublasStatus_t  CUDAAPI tcublasZgemv_v2(cublasHandle_t, cublasOperation_t, int, int, const cuDoubleComplex *, const cuDoubleComplex *, int, const cuDoubleComplex *, int, const cuDoubleComplex *, cuDoubleComplex *, int);
extern tcublasZgemv_v2 *cublasZgemv_v2;
typedef cublasStatus_t  CUDAAPI tcublasSgbmv_v2(cublasHandle_t, cublasOperation_t, int, int, int, int, const float *, const float *, int, const float *, int, const float *, float *, int);
extern tcublasSgbmv_v2 *cublasSgbmv_v2;
typedef cublasStatus_t  CUDAAPI tcublasDgbmv_v2(cublasHandle_t, cublasOperation_t, int, int, int, int, const double *, const double *, int, const double *, int, const double *, double *, int);
extern tcublasDgbmv_v2 *cublasDgbmv_v2;
typedef cublasStatus_t  CUDAAPI tcublasCgbmv_v2(cublasHandle_t, cublasOperation_t, int, int, int, int, const cuComplex *, const cuComplex *, int, const cuComplex *, int, const cuComplex *, cuComplex *, int);
extern tcublasCgbmv_v2 *cublasCgbmv_v2;
typedef cublasStatus_t  CUDAAPI tcublasZgbmv_v2(cublasHandle_t, cublasOperation_t, int, int, int, int, const cuDoubleComplex *, const cuDoubleComplex *, int, const cuDoubleComplex *, int, const cuDoubleComplex *, cuDoubleComplex *, int);
extern tcublasZgbmv_v2 *cublasZgbmv_v2;
typedef cublasStatus_t  CUDAAPI tcublasStrmv_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, const float *, int, float *, int);
extern tcublasStrmv_v2 *cublasStrmv_v2;
typedef cublasStatus_t  CUDAAPI tcublasDtrmv_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, const double *, int, double *, int);
extern tcublasDtrmv_v2 *cublasDtrmv_v2;
typedef cublasStatus_t  CUDAAPI tcublasCtrmv_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, const cuComplex *, int, cuComplex *, int);
extern tcublasCtrmv_v2 *cublasCtrmv_v2;
typedef cublasStatus_t  CUDAAPI tcublasZtrmv_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, const cuDoubleComplex *, int, cuDoubleComplex *, int);
extern tcublasZtrmv_v2 *cublasZtrmv_v2;
typedef cublasStatus_t  CUDAAPI tcublasStbmv_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, int, const float *, int, float *, int);
extern tcublasStbmv_v2 *cublasStbmv_v2;
typedef cublasStatus_t  CUDAAPI tcublasDtbmv_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, int, const double *, int, double *, int);
extern tcublasDtbmv_v2 *cublasDtbmv_v2;
typedef cublasStatus_t  CUDAAPI tcublasCtbmv_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, int, const cuComplex *, int, cuComplex *, int);
extern tcublasCtbmv_v2 *cublasCtbmv_v2;
typedef cublasStatus_t  CUDAAPI tcublasZtbmv_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, int, const cuDoubleComplex *, int, cuDoubleComplex *, int);
extern tcublasZtbmv_v2 *cublasZtbmv_v2;
typedef cublasStatus_t  CUDAAPI tcublasStpmv_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, const float *, float *, int);
extern tcublasStpmv_v2 *cublasStpmv_v2;
typedef cublasStatus_t  CUDAAPI tcublasDtpmv_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, const double *, double *, int);
extern tcublasDtpmv_v2 *cublasDtpmv_v2;
typedef cublasStatus_t  CUDAAPI tcublasCtpmv_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, const cuComplex *, cuComplex *, int);
extern tcublasCtpmv_v2 *cublasCtpmv_v2;
typedef cublasStatus_t  CUDAAPI tcublasZtpmv_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, const cuDoubleComplex *, cuDoubleComplex *, int);
extern tcublasZtpmv_v2 *cublasZtpmv_v2;
typedef cublasStatus_t  CUDAAPI tcublasStrsv_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, const float *, int, float *, int);
extern tcublasStrsv_v2 *cublasStrsv_v2;
typedef cublasStatus_t  CUDAAPI tcublasDtrsv_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, const double *, int, double *, int);
extern tcublasDtrsv_v2 *cublasDtrsv_v2;
typedef cublasStatus_t  CUDAAPI tcublasCtrsv_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, const cuComplex *, int, cuComplex *, int);
extern tcublasCtrsv_v2 *cublasCtrsv_v2;
typedef cublasStatus_t  CUDAAPI tcublasZtrsv_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, const cuDoubleComplex *, int, cuDoubleComplex *, int);
extern tcublasZtrsv_v2 *cublasZtrsv_v2;
typedef cublasStatus_t  CUDAAPI tcublasStpsv_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, const float *, float *, int);
extern tcublasStpsv_v2 *cublasStpsv_v2;
typedef cublasStatus_t  CUDAAPI tcublasDtpsv_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, const double *, double *, int);
extern tcublasDtpsv_v2 *cublasDtpsv_v2;
typedef cublasStatus_t  CUDAAPI tcublasCtpsv_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, const cuComplex *, cuComplex *, int);
extern tcublasCtpsv_v2 *cublasCtpsv_v2;
typedef cublasStatus_t  CUDAAPI tcublasZtpsv_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, const cuDoubleComplex *, cuDoubleComplex *, int);
extern tcublasZtpsv_v2 *cublasZtpsv_v2;
typedef cublasStatus_t  CUDAAPI tcublasStbsv_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, int, const float *, int, float *, int);
extern tcublasStbsv_v2 *cublasStbsv_v2;
typedef cublasStatus_t  CUDAAPI tcublasDtbsv_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, int, const double *, int, double *, int);
extern tcublasDtbsv_v2 *cublasDtbsv_v2;
typedef cublasStatus_t  CUDAAPI tcublasCtbsv_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, int, const cuComplex *, int, cuComplex *, int);
extern tcublasCtbsv_v2 *cublasCtbsv_v2;
typedef cublasStatus_t  CUDAAPI tcublasZtbsv_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, int, const cuDoubleComplex *, int, cuDoubleComplex *, int);
extern tcublasZtbsv_v2 *cublasZtbsv_v2;
typedef cublasStatus_t  CUDAAPI tcublasSsymv_v2(cublasHandle_t, cublasFillMode_t, int, const float *, const float *, int, const float *, int, const float *, float *, int);
extern tcublasSsymv_v2 *cublasSsymv_v2;
typedef cublasStatus_t  CUDAAPI tcublasDsymv_v2(cublasHandle_t, cublasFillMode_t, int, const double *, const double *, int, const double *, int, const double *, double *, int);
extern tcublasDsymv_v2 *cublasDsymv_v2;
typedef cublasStatus_t  CUDAAPI tcublasCsymv_v2(cublasHandle_t, cublasFillMode_t, int, const cuComplex *, const cuComplex *, int, const cuComplex *, int, const cuComplex *, cuComplex *, int);
extern tcublasCsymv_v2 *cublasCsymv_v2;
typedef cublasStatus_t  CUDAAPI tcublasZsymv_v2(cublasHandle_t, cublasFillMode_t, int, const cuDoubleComplex *, const cuDoubleComplex *, int, const cuDoubleComplex *, int, const cuDoubleComplex *, cuDoubleComplex *, int);
extern tcublasZsymv_v2 *cublasZsymv_v2;
typedef cublasStatus_t  CUDAAPI tcublasChemv_v2(cublasHandle_t, cublasFillMode_t, int, const cuComplex *, const cuComplex *, int, const cuComplex *, int, const cuComplex *, cuComplex *, int);
extern tcublasChemv_v2 *cublasChemv_v2;
typedef cublasStatus_t  CUDAAPI tcublasZhemv_v2(cublasHandle_t, cublasFillMode_t, int, const cuDoubleComplex *, const cuDoubleComplex *, int, const cuDoubleComplex *, int, const cuDoubleComplex *, cuDoubleComplex *, int);
extern tcublasZhemv_v2 *cublasZhemv_v2;
typedef cublasStatus_t  CUDAAPI tcublasSsbmv_v2(cublasHandle_t, cublasFillMode_t, int, int, const float *, const float *, int, const float *, int, const float *, float *, int);
extern tcublasSsbmv_v2 *cublasSsbmv_v2;
typedef cublasStatus_t  CUDAAPI tcublasDsbmv_v2(cublasHandle_t, cublasFillMode_t, int, int, const double *, const double *, int, const double *, int, const double *, double *, int);
extern tcublasDsbmv_v2 *cublasDsbmv_v2;
typedef cublasStatus_t  CUDAAPI tcublasChbmv_v2(cublasHandle_t, cublasFillMode_t, int, int, const cuComplex *, const cuComplex *, int, const cuComplex *, int, const cuComplex *, cuComplex *, int);
extern tcublasChbmv_v2 *cublasChbmv_v2;
typedef cublasStatus_t  CUDAAPI tcublasZhbmv_v2(cublasHandle_t, cublasFillMode_t, int, int, const cuDoubleComplex *, const cuDoubleComplex *, int, const cuDoubleComplex *, int, const cuDoubleComplex *, cuDoubleComplex *, int);
extern tcublasZhbmv_v2 *cublasZhbmv_v2;
typedef cublasStatus_t  CUDAAPI tcublasSspmv_v2(cublasHandle_t, cublasFillMode_t, int, const float *, const float *, const float *, int, const float *, float *, int);
extern tcublasSspmv_v2 *cublasSspmv_v2;
typedef cublasStatus_t  CUDAAPI tcublasDspmv_v2(cublasHandle_t, cublasFillMode_t, int, const double *, const double *, const double *, int, const double *, double *, int);
extern tcublasDspmv_v2 *cublasDspmv_v2;
typedef cublasStatus_t  CUDAAPI tcublasChpmv_v2(cublasHandle_t, cublasFillMode_t, int, const cuComplex *, const cuComplex *, const cuComplex *, int, const cuComplex *, cuComplex *, int);
extern tcublasChpmv_v2 *cublasChpmv_v2;
typedef cublasStatus_t  CUDAAPI tcublasZhpmv_v2(cublasHandle_t, cublasFillMode_t, int, const cuDoubleComplex *, const cuDoubleComplex *, const cuDoubleComplex *, int, const cuDoubleComplex *, cuDoubleComplex *, int);
extern tcublasZhpmv_v2 *cublasZhpmv_v2;
typedef cublasStatus_t  CUDAAPI tcublasSger_v2(cublasHandle_t, int, int, const float *, const float *, int, const float *, int, float *, int);
extern tcublasSger_v2 *cublasSger_v2;
typedef cublasStatus_t  CUDAAPI tcublasDger_v2(cublasHandle_t, int, int, const double *, const double *, int, const double *, int, double *, int);
extern tcublasDger_v2 *cublasDger_v2;
typedef cublasStatus_t  CUDAAPI tcublasCgeru_v2(cublasHandle_t, int, int, const cuComplex *, const cuComplex *, int, const cuComplex *, int, cuComplex *, int);
extern tcublasCgeru_v2 *cublasCgeru_v2;
typedef cublasStatus_t  CUDAAPI tcublasCgerc_v2(cublasHandle_t, int, int, const cuComplex *, const cuComplex *, int, const cuComplex *, int, cuComplex *, int);
extern tcublasCgerc_v2 *cublasCgerc_v2;
typedef cublasStatus_t  CUDAAPI tcublasZgeru_v2(cublasHandle_t, int, int, const cuDoubleComplex *, const cuDoubleComplex *, int, const cuDoubleComplex *, int, cuDoubleComplex *, int);
extern tcublasZgeru_v2 *cublasZgeru_v2;
typedef cublasStatus_t  CUDAAPI tcublasZgerc_v2(cublasHandle_t, int, int, const cuDoubleComplex *, const cuDoubleComplex *, int, const cuDoubleComplex *, int, cuDoubleComplex *, int);
extern tcublasZgerc_v2 *cublasZgerc_v2;
typedef cublasStatus_t  CUDAAPI tcublasSsyr_v2(cublasHandle_t, cublasFillMode_t, int, const float *, const float *, int, float *, int);
extern tcublasSsyr_v2 *cublasSsyr_v2;
typedef cublasStatus_t  CUDAAPI tcublasDsyr_v2(cublasHandle_t, cublasFillMode_t, int, const double *, const double *, int, double *, int);
extern tcublasDsyr_v2 *cublasDsyr_v2;
typedef cublasStatus_t  CUDAAPI tcublasCsyr_v2(cublasHandle_t, cublasFillMode_t, int, const cuComplex *, const cuComplex *, int, cuComplex *, int);
extern tcublasCsyr_v2 *cublasCsyr_v2;
typedef cublasStatus_t  CUDAAPI tcublasZsyr_v2(cublasHandle_t, cublasFillMode_t, int, const cuDoubleComplex *, const cuDoubleComplex *, int, cuDoubleComplex *, int);
extern tcublasZsyr_v2 *cublasZsyr_v2;
typedef cublasStatus_t  CUDAAPI tcublasCher_v2(cublasHandle_t, cublasFillMode_t, int, const float *, const cuComplex *, int, cuComplex *, int);
extern tcublasCher_v2 *cublasCher_v2;
typedef cublasStatus_t  CUDAAPI tcublasZher_v2(cublasHandle_t, cublasFillMode_t, int, const double *, const cuDoubleComplex *, int, cuDoubleComplex *, int);
extern tcublasZher_v2 *cublasZher_v2;
typedef cublasStatus_t  CUDAAPI tcublasSspr_v2(cublasHandle_t, cublasFillMode_t, int, const float *, const float *, int, float *);
extern tcublasSspr_v2 *cublasSspr_v2;
typedef cublasStatus_t  CUDAAPI tcublasDspr_v2(cublasHandle_t, cublasFillMode_t, int, const double *, const double *, int, double *);
extern tcublasDspr_v2 *cublasDspr_v2;
typedef cublasStatus_t  CUDAAPI tcublasChpr_v2(cublasHandle_t, cublasFillMode_t, int, const float *, const cuComplex *, int, cuComplex *);
extern tcublasChpr_v2 *cublasChpr_v2;
typedef cublasStatus_t  CUDAAPI tcublasZhpr_v2(cublasHandle_t, cublasFillMode_t, int, const double *, const cuDoubleComplex *, int, cuDoubleComplex *);
extern tcublasZhpr_v2 *cublasZhpr_v2;
typedef cublasStatus_t  CUDAAPI tcublasSsyr2_v2(cublasHandle_t, cublasFillMode_t, int, const float *, const float *, int, const float *, int, float *, int);
extern tcublasSsyr2_v2 *cublasSsyr2_v2;
typedef cublasStatus_t  CUDAAPI tcublasDsyr2_v2(cublasHandle_t, cublasFillMode_t, int, const double *, const double *, int, const double *, int, double *, int);
extern tcublasDsyr2_v2 *cublasDsyr2_v2;
typedef cublasStatus_t  CUDAAPI tcublasCsyr2_v2(cublasHandle_t, cublasFillMode_t, int, const cuComplex *, const cuComplex *, int, const cuComplex *, int, cuComplex *, int);
extern tcublasCsyr2_v2 *cublasCsyr2_v2;
typedef cublasStatus_t  CUDAAPI tcublasZsyr2_v2(cublasHandle_t, cublasFillMode_t, int, const cuDoubleComplex *, const cuDoubleComplex *, int, const cuDoubleComplex *, int, cuDoubleComplex *, int);
extern tcublasZsyr2_v2 *cublasZsyr2_v2;
typedef cublasStatus_t  CUDAAPI tcublasCher2_v2(cublasHandle_t, cublasFillMode_t, int, const cuComplex *, const cuComplex *, int, const cuComplex *, int, cuComplex *, int);
extern tcublasCher2_v2 *cublasCher2_v2;
typedef cublasStatus_t  CUDAAPI tcublasZher2_v2(cublasHandle_t, cublasFillMode_t, int, const cuDoubleComplex *, const cuDoubleComplex *, int, const cuDoubleComplex *, int, cuDoubleComplex *, int);
extern tcublasZher2_v2 *cublasZher2_v2;
typedef cublasStatus_t  CUDAAPI tcublasSspr2_v2(cublasHandle_t, cublasFillMode_t, int, const float *, const float *, int, const float *, int, float *);
extern tcublasSspr2_v2 *cublasSspr2_v2;
typedef cublasStatus_t  CUDAAPI tcublasDspr2_v2(cublasHandle_t, cublasFillMode_t, int, const double *, const double *, int, const double *, int, double *);
extern tcublasDspr2_v2 *cublasDspr2_v2;
typedef cublasStatus_t  CUDAAPI tcublasChpr2_v2(cublasHandle_t, cublasFillMode_t, int, const cuComplex *, const cuComplex *, int, const cuComplex *, int, cuComplex *);
extern tcublasChpr2_v2 *cublasChpr2_v2;
typedef cublasStatus_t  CUDAAPI tcublasZhpr2_v2(cublasHandle_t, cublasFillMode_t, int, const cuDoubleComplex *, const cuDoubleComplex *, int, const cuDoubleComplex *, int, cuDoubleComplex *);
extern tcublasZhpr2_v2 *cublasZhpr2_v2;
typedef cublasStatus_t  CUDAAPI tcublasSgemm_v2(cublasHandle_t, cublasOperation_t, cublasOperation_t, int, int, int, const float *, const float *, int, const float *, int, const float *, float *, int);
extern tcublasSgemm_v2 *cublasSgemm_v2;
typedef cublasStatus_t  CUDAAPI tcublasDgemm_v2(cublasHandle_t, cublasOperation_t, cublasOperation_t, int, int, int, const double *, const double *, int, const double *, int, const double *, double *, int);
extern tcublasDgemm_v2 *cublasDgemm_v2;
typedef cublasStatus_t  CUDAAPI tcublasCgemm_v2(cublasHandle_t, cublasOperation_t, cublasOperation_t, int, int, int, const cuComplex *, const cuComplex *, int, const cuComplex *, int, const cuComplex *, cuComplex *, int);
extern tcublasCgemm_v2 *cublasCgemm_v2;
typedef cublasStatus_t  CUDAAPI tcublasCgemm3m(cublasHandle_t, cublasOperation_t, cublasOperation_t, int, int, int, const cuComplex *, const cuComplex *, int, const cuComplex *, int, const cuComplex *, cuComplex *, int);
extern tcublasCgemm3m *cublasCgemm3m;
typedef cublasStatus_t  CUDAAPI tcublasCgemm3mEx(cublasHandle_t, cublasOperation_t, cublasOperation_t, int, int, int, const cuComplex *, const void *, cudaDataType, int, const void *, cudaDataType, int, const cuComplex *, void *, cudaDataType, int);
extern tcublasCgemm3mEx *cublasCgemm3mEx;
typedef cublasStatus_t  CUDAAPI tcublasZgemm_v2(cublasHandle_t, cublasOperation_t, cublasOperation_t, int, int, int, const cuDoubleComplex *, const cuDoubleComplex *, int, const cuDoubleComplex *, int, const cuDoubleComplex *, cuDoubleComplex *, int);
extern tcublasZgemm_v2 *cublasZgemm_v2;
typedef cublasStatus_t  CUDAAPI tcublasZgemm3m(cublasHandle_t, cublasOperation_t, cublasOperation_t, int, int, int, const cuDoubleComplex *, const cuDoubleComplex *, int, const cuDoubleComplex *, int, const cuDoubleComplex *, cuDoubleComplex *, int);
extern tcublasZgemm3m *cublasZgemm3m;
typedef cublasStatus_t  CUDAAPI tcublasSgemmEx(cublasHandle_t, cublasOperation_t, cublasOperation_t, int, int, int, const float *, const void *, cudaDataType, int, const void *, cudaDataType, int, const float *, void *, cudaDataType, int);
extern tcublasSgemmEx *cublasSgemmEx;
typedef cublasStatus_t  CUDAAPI tcublasGemmEx(cublasHandle_t, cublasOperation_t, cublasOperation_t, int, int, int, const void *, const void *, cudaDataType, int, const void *, cudaDataType, int, const void *, void *, cudaDataType, int, cublasComputeType_t, cublasGemmAlgo_t);
extern tcublasGemmEx *cublasGemmEx;
typedef cublasStatus_t  CUDAAPI tcublasCgemmEx(cublasHandle_t, cublasOperation_t, cublasOperation_t, int, int, int, const cuComplex *, const void *, cudaDataType, int, const void *, cudaDataType, int, const cuComplex *, void *, cudaDataType, int);
extern tcublasCgemmEx *cublasCgemmEx;
typedef cublasStatus_t  CUDAAPI tcublasUint8gemmBias(cublasHandle_t, cublasOperation_t, cublasOperation_t, cublasOperation_t, int, int, int, const unsigned char *, int, int, const unsigned char *, int, int, unsigned char *, int, int, int, int);
extern tcublasUint8gemmBias *cublasUint8gemmBias;
typedef cublasStatus_t  CUDAAPI tcublasSsyrk_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, int, int, const float *, const float *, int, const float *, float *, int);
extern tcublasSsyrk_v2 *cublasSsyrk_v2;
typedef cublasStatus_t  CUDAAPI tcublasDsyrk_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, int, int, const double *, const double *, int, const double *, double *, int);
extern tcublasDsyrk_v2 *cublasDsyrk_v2;
typedef cublasStatus_t  CUDAAPI tcublasCsyrk_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, int, int, const cuComplex *, const cuComplex *, int, const cuComplex *, cuComplex *, int);
extern tcublasCsyrk_v2 *cublasCsyrk_v2;
typedef cublasStatus_t  CUDAAPI tcublasZsyrk_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, int, int, const cuDoubleComplex *, const cuDoubleComplex *, int, const cuDoubleComplex *, cuDoubleComplex *, int);
extern tcublasZsyrk_v2 *cublasZsyrk_v2;
typedef cublasStatus_t  CUDAAPI tcublasCsyrkEx(cublasHandle_t, cublasFillMode_t, cublasOperation_t, int, int, const cuComplex *, const void *, cudaDataType, int, const cuComplex *, void *, cudaDataType, int);
extern tcublasCsyrkEx *cublasCsyrkEx;
typedef cublasStatus_t  CUDAAPI tcublasCsyrk3mEx(cublasHandle_t, cublasFillMode_t, cublasOperation_t, int, int, const cuComplex *, const void *, cudaDataType, int, const cuComplex *, void *, cudaDataType, int);
extern tcublasCsyrk3mEx *cublasCsyrk3mEx;
typedef cublasStatus_t  CUDAAPI tcublasCherk_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, int, int, const float *, const cuComplex *, int, const float *, cuComplex *, int);
extern tcublasCherk_v2 *cublasCherk_v2;
typedef cublasStatus_t  CUDAAPI tcublasZherk_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, int, int, const double *, const cuDoubleComplex *, int, const double *, cuDoubleComplex *, int);
extern tcublasZherk_v2 *cublasZherk_v2;
typedef cublasStatus_t  CUDAAPI tcublasCherkEx(cublasHandle_t, cublasFillMode_t, cublasOperation_t, int, int, const float *, const void *, cudaDataType, int, const float *, void *, cudaDataType, int);
extern tcublasCherkEx *cublasCherkEx;
typedef cublasStatus_t  CUDAAPI tcublasCherk3mEx(cublasHandle_t, cublasFillMode_t, cublasOperation_t, int, int, const float *, const void *, cudaDataType, int, const float *, void *, cudaDataType, int);
extern tcublasCherk3mEx *cublasCherk3mEx;
typedef cublasStatus_t  CUDAAPI tcublasSsyr2k_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, int, int, const float *, const float *, int, const float *, int, const float *, float *, int);
extern tcublasSsyr2k_v2 *cublasSsyr2k_v2;
typedef cublasStatus_t  CUDAAPI tcublasDsyr2k_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, int, int, const double *, const double *, int, const double *, int, const double *, double *, int);
extern tcublasDsyr2k_v2 *cublasDsyr2k_v2;
typedef cublasStatus_t  CUDAAPI tcublasCsyr2k_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, int, int, const cuComplex *, const cuComplex *, int, const cuComplex *, int, const cuComplex *, cuComplex *, int);
extern tcublasCsyr2k_v2 *cublasCsyr2k_v2;
typedef cublasStatus_t  CUDAAPI tcublasZsyr2k_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, int, int, const cuDoubleComplex *, const cuDoubleComplex *, int, const cuDoubleComplex *, int, const cuDoubleComplex *, cuDoubleComplex *, int);
extern tcublasZsyr2k_v2 *cublasZsyr2k_v2;
typedef cublasStatus_t  CUDAAPI tcublasCher2k_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, int, int, const cuComplex *, const cuComplex *, int, const cuComplex *, int, const float *, cuComplex *, int);
extern tcublasCher2k_v2 *cublasCher2k_v2;
typedef cublasStatus_t  CUDAAPI tcublasZher2k_v2(cublasHandle_t, cublasFillMode_t, cublasOperation_t, int, int, const cuDoubleComplex *, const cuDoubleComplex *, int, const cuDoubleComplex *, int, const double *, cuDoubleComplex *, int);
extern tcublasZher2k_v2 *cublasZher2k_v2;
typedef cublasStatus_t  CUDAAPI tcublasSsyrkx(cublasHandle_t, cublasFillMode_t, cublasOperation_t, int, int, const float *, const float *, int, const float *, int, const float *, float *, int);
extern tcublasSsyrkx *cublasSsyrkx;
typedef cublasStatus_t  CUDAAPI tcublasDsyrkx(cublasHandle_t, cublasFillMode_t, cublasOperation_t, int, int, const double *, const double *, int, const double *, int, const double *, double *, int);
extern tcublasDsyrkx *cublasDsyrkx;
typedef cublasStatus_t  CUDAAPI tcublasCsyrkx(cublasHandle_t, cublasFillMode_t, cublasOperation_t, int, int, const cuComplex *, const cuComplex *, int, const cuComplex *, int, const cuComplex *, cuComplex *, int);
extern tcublasCsyrkx *cublasCsyrkx;
typedef cublasStatus_t  CUDAAPI tcublasZsyrkx(cublasHandle_t, cublasFillMode_t, cublasOperation_t, int, int, const cuDoubleComplex *, const cuDoubleComplex *, int, const cuDoubleComplex *, int, const cuDoubleComplex *, cuDoubleComplex *, int);
extern tcublasZsyrkx *cublasZsyrkx;
typedef cublasStatus_t  CUDAAPI tcublasCherkx(cublasHandle_t, cublasFillMode_t, cublasOperation_t, int, int, const cuComplex *, const cuComplex *, int, const cuComplex *, int, const float *, cuComplex *, int);
extern tcublasCherkx *cublasCherkx;
typedef cublasStatus_t  CUDAAPI tcublasZherkx(cublasHandle_t, cublasFillMode_t, cublasOperation_t, int, int, const cuDoubleComplex *, const cuDoubleComplex *, int, const cuDoubleComplex *, int, const double *, cuDoubleComplex *, int);
extern tcublasZherkx *cublasZherkx;
typedef cublasStatus_t  CUDAAPI tcublasSsymm_v2(cublasHandle_t, cublasSideMode_t, cublasFillMode_t, int, int, const float *, const float *, int, const float *, int, const float *, float *, int);
extern tcublasSsymm_v2 *cublasSsymm_v2;
typedef cublasStatus_t  CUDAAPI tcublasDsymm_v2(cublasHandle_t, cublasSideMode_t, cublasFillMode_t, int, int, const double *, const double *, int, const double *, int, const double *, double *, int);
extern tcublasDsymm_v2 *cublasDsymm_v2;
typedef cublasStatus_t  CUDAAPI tcublasCsymm_v2(cublasHandle_t, cublasSideMode_t, cublasFillMode_t, int, int, const cuComplex *, const cuComplex *, int, const cuComplex *, int, const cuComplex *, cuComplex *, int);
extern tcublasCsymm_v2 *cublasCsymm_v2;
typedef cublasStatus_t  CUDAAPI tcublasZsymm_v2(cublasHandle_t, cublasSideMode_t, cublasFillMode_t, int, int, const cuDoubleComplex *, const cuDoubleComplex *, int, const cuDoubleComplex *, int, const cuDoubleComplex *, cuDoubleComplex *, int);
extern tcublasZsymm_v2 *cublasZsymm_v2;
typedef cublasStatus_t  CUDAAPI tcublasChemm_v2(cublasHandle_t, cublasSideMode_t, cublasFillMode_t, int, int, const cuComplex *, const cuComplex *, int, const cuComplex *, int, const cuComplex *, cuComplex *, int);
extern tcublasChemm_v2 *cublasChemm_v2;
typedef cublasStatus_t  CUDAAPI tcublasZhemm_v2(cublasHandle_t, cublasSideMode_t, cublasFillMode_t, int, int, const cuDoubleComplex *, const cuDoubleComplex *, int, const cuDoubleComplex *, int, const cuDoubleComplex *, cuDoubleComplex *, int);
extern tcublasZhemm_v2 *cublasZhemm_v2;
typedef cublasStatus_t  CUDAAPI tcublasStrsm_v2(cublasHandle_t, cublasSideMode_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, int, const float *, const float *, int, float *, int);
extern tcublasStrsm_v2 *cublasStrsm_v2;
typedef cublasStatus_t  CUDAAPI tcublasDtrsm_v2(cublasHandle_t, cublasSideMode_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, int, const double *, const double *, int, double *, int);
extern tcublasDtrsm_v2 *cublasDtrsm_v2;
typedef cublasStatus_t  CUDAAPI tcublasCtrsm_v2(cublasHandle_t, cublasSideMode_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, int, const cuComplex *, const cuComplex *, int, cuComplex *, int);
extern tcublasCtrsm_v2 *cublasCtrsm_v2;
typedef cublasStatus_t  CUDAAPI tcublasZtrsm_v2(cublasHandle_t, cublasSideMode_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, int, const cuDoubleComplex *, const cuDoubleComplex *, int, cuDoubleComplex *, int);
extern tcublasZtrsm_v2 *cublasZtrsm_v2;
typedef cublasStatus_t  CUDAAPI tcublasStrmm_v2(cublasHandle_t, cublasSideMode_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, int, const float *, const float *, int, const float *, int, float *, int);
extern tcublasStrmm_v2 *cublasStrmm_v2;
typedef cublasStatus_t  CUDAAPI tcublasDtrmm_v2(cublasHandle_t, cublasSideMode_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, int, const double *, const double *, int, const double *, int, double *, int);
extern tcublasDtrmm_v2 *cublasDtrmm_v2;
typedef cublasStatus_t  CUDAAPI tcublasCtrmm_v2(cublasHandle_t, cublasSideMode_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, int, const cuComplex *, const cuComplex *, int, const cuComplex *, int, cuComplex *, int);
extern tcublasCtrmm_v2 *cublasCtrmm_v2;
typedef cublasStatus_t  CUDAAPI tcublasZtrmm_v2(cublasHandle_t, cublasSideMode_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, int, const cuDoubleComplex *, const cuDoubleComplex *, int, const cuDoubleComplex *, int, cuDoubleComplex *, int);
extern tcublasZtrmm_v2 *cublasZtrmm_v2;
typedef cublasStatus_t  CUDAAPI tcublasSgemmBatched(cublasHandle_t, cublasOperation_t, cublasOperation_t, int, int, int, const float *, const float *const *, int, const float *const *, int, const float *, float *const *, int, int);
extern tcublasSgemmBatched *cublasSgemmBatched;
typedef cublasStatus_t  CUDAAPI tcublasDgemmBatched(cublasHandle_t, cublasOperation_t, cublasOperation_t, int, int, int, const double *, const double *const *, int, const double *const *, int, const double *, double *const *, int, int);
extern tcublasDgemmBatched *cublasDgemmBatched;
typedef cublasStatus_t  CUDAAPI tcublasCgemmBatched(cublasHandle_t, cublasOperation_t, cublasOperation_t, int, int, int, const cuComplex *, const cuComplex *const *, int, const cuComplex *const *, int, const cuComplex *, cuComplex *const *, int, int);
extern tcublasCgemmBatched *cublasCgemmBatched;
typedef cublasStatus_t  CUDAAPI tcublasCgemm3mBatched(cublasHandle_t, cublasOperation_t, cublasOperation_t, int, int, int, const cuComplex *, const cuComplex *const *, int, const cuComplex *const *, int, const cuComplex *, cuComplex *const *, int, int);
extern tcublasCgemm3mBatched *cublasCgemm3mBatched;
typedef cublasStatus_t  CUDAAPI tcublasZgemmBatched(cublasHandle_t, cublasOperation_t, cublasOperation_t, int, int, int, const cuDoubleComplex *, const cuDoubleComplex *const *, int, const cuDoubleComplex *const *, int, const cuDoubleComplex *, cuDoubleComplex *const *, int, int);
extern tcublasZgemmBatched *cublasZgemmBatched;
typedef cublasStatus_t  CUDAAPI tcublasGemmBatchedEx(cublasHandle_t, cublasOperation_t, cublasOperation_t, int, int, int, const void *, const void *const *, cudaDataType, int, const void *const *, cudaDataType, int, const void *, void *const *, cudaDataType, int, int, cublasComputeType_t, cublasGemmAlgo_t);
extern tcublasGemmBatchedEx *cublasGemmBatchedEx;
typedef cublasStatus_t  CUDAAPI tcublasGemmStridedBatchedEx(cublasHandle_t, cublasOperation_t, cublasOperation_t, int, int, int, const void *, const void *, cudaDataType, int, long long, const void *, cudaDataType, int, long long, const void *, void *, cudaDataType, int, long long, int, cublasComputeType_t, cublasGemmAlgo_t);
extern tcublasGemmStridedBatchedEx *cublasGemmStridedBatchedEx;
typedef cublasStatus_t  CUDAAPI tcublasSgemmStridedBatched(cublasHandle_t, cublasOperation_t, cublasOperation_t, int, int, int, const float *, const float *, int, long long, const float *, int, long long, const float *, float *, int, long long, int);
extern tcublasSgemmStridedBatched *cublasSgemmStridedBatched;
typedef cublasStatus_t  CUDAAPI tcublasDgemmStridedBatched(cublasHandle_t, cublasOperation_t, cublasOperation_t, int, int, int, const double *, const double *, int, long long, const double *, int, long long, const double *, double *, int, long long, int);
extern tcublasDgemmStridedBatched *cublasDgemmStridedBatched;
typedef cublasStatus_t  CUDAAPI tcublasCgemmStridedBatched(cublasHandle_t, cublasOperation_t, cublasOperation_t, int, int, int, const cuComplex *, const cuComplex *, int, long long, const cuComplex *, int, long long, const cuComplex *, cuComplex *, int, long long, int);
extern tcublasCgemmStridedBatched *cublasCgemmStridedBatched;
typedef cublasStatus_t  CUDAAPI tcublasCgemm3mStridedBatched(cublasHandle_t, cublasOperation_t, cublasOperation_t, int, int, int, const cuComplex *, const cuComplex *, int, long long, const cuComplex *, int, long long, const cuComplex *, cuComplex *, int, long long, int);
extern tcublasCgemm3mStridedBatched *cublasCgemm3mStridedBatched;
typedef cublasStatus_t  CUDAAPI tcublasZgemmStridedBatched(cublasHandle_t, cublasOperation_t, cublasOperation_t, int, int, int, const cuDoubleComplex *, const cuDoubleComplex *, int, long long, const cuDoubleComplex *, int, long long, const cuDoubleComplex *, cuDoubleComplex *, int, long long, int);
extern tcublasZgemmStridedBatched *cublasZgemmStridedBatched;
typedef cublasStatus_t  CUDAAPI tcublasSgeam(cublasHandle_t, cublasOperation_t, cublasOperation_t, int, int, const float *, const float *, int, const float *, const float *, int, float *, int);
extern tcublasSgeam *cublasSgeam;
typedef cublasStatus_t  CUDAAPI tcublasDgeam(cublasHandle_t, cublasOperation_t, cublasOperation_t, int, int, const double *, const double *, int, const double *, const double *, int, double *, int);
extern tcublasDgeam *cublasDgeam;
typedef cublasStatus_t  CUDAAPI tcublasCgeam(cublasHandle_t, cublasOperation_t, cublasOperation_t, int, int, const cuComplex *, const cuComplex *, int, const cuComplex *, const cuComplex *, int, cuComplex *, int);
extern tcublasCgeam *cublasCgeam;
typedef cublasStatus_t  CUDAAPI tcublasZgeam(cublasHandle_t, cublasOperation_t, cublasOperation_t, int, int, const cuDoubleComplex *, const cuDoubleComplex *, int, const cuDoubleComplex *, const cuDoubleComplex *, int, cuDoubleComplex *, int);
extern tcublasZgeam *cublasZgeam;
typedef cublasStatus_t  CUDAAPI tcublasSgetrfBatched(cublasHandle_t, int, float *const *, int, int *, int *, int);
extern tcublasSgetrfBatched *cublasSgetrfBatched;
typedef cublasStatus_t  CUDAAPI tcublasDgetrfBatched(cublasHandle_t, int, double *const *, int, int *, int *, int);
extern tcublasDgetrfBatched *cublasDgetrfBatched;
typedef cublasStatus_t  CUDAAPI tcublasCgetrfBatched(cublasHandle_t, int, cuComplex *const *, int, int *, int *, int);
extern tcublasCgetrfBatched *cublasCgetrfBatched;
typedef cublasStatus_t  CUDAAPI tcublasZgetrfBatched(cublasHandle_t, int, cuDoubleComplex *const *, int, int *, int *, int);
extern tcublasZgetrfBatched *cublasZgetrfBatched;
typedef cublasStatus_t  CUDAAPI tcublasSgetriBatched(cublasHandle_t, int, const float *const *, int, const int *, float *const *, int, int *, int);
extern tcublasSgetriBatched *cublasSgetriBatched;
typedef cublasStatus_t  CUDAAPI tcublasDgetriBatched(cublasHandle_t, int, const double *const *, int, const int *, double *const *, int, int *, int);
extern tcublasDgetriBatched *cublasDgetriBatched;
typedef cublasStatus_t  CUDAAPI tcublasCgetriBatched(cublasHandle_t, int, const cuComplex *const *, int, const int *, cuComplex *const *, int, int *, int);
extern tcublasCgetriBatched *cublasCgetriBatched;
typedef cublasStatus_t  CUDAAPI tcublasZgetriBatched(cublasHandle_t, int, const cuDoubleComplex *const *, int, const int *, cuDoubleComplex *const *, int, int *, int);
extern tcublasZgetriBatched *cublasZgetriBatched;
typedef cublasStatus_t  CUDAAPI tcublasSgetrsBatched(cublasHandle_t, cublasOperation_t, int, int, const float *const *, int, const int *, float *const *, int, int *, int);
extern tcublasSgetrsBatched *cublasSgetrsBatched;
typedef cublasStatus_t  CUDAAPI tcublasDgetrsBatched(cublasHandle_t, cublasOperation_t, int, int, const double *const *, int, const int *, double *const *, int, int *, int);
extern tcublasDgetrsBatched *cublasDgetrsBatched;
typedef cublasStatus_t  CUDAAPI tcublasCgetrsBatched(cublasHandle_t, cublasOperation_t, int, int, const cuComplex *const *, int, const int *, cuComplex *const *, int, int *, int);
extern tcublasCgetrsBatched *cublasCgetrsBatched;
typedef cublasStatus_t  CUDAAPI tcublasZgetrsBatched(cublasHandle_t, cublasOperation_t, int, int, const cuDoubleComplex *const *, int, const int *, cuDoubleComplex *const *, int, int *, int);
extern tcublasZgetrsBatched *cublasZgetrsBatched;
typedef cublasStatus_t  CUDAAPI tcublasStrsmBatched(cublasHandle_t, cublasSideMode_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, int, const float *, const float *const *, int, float *const *, int, int);
extern tcublasStrsmBatched *cublasStrsmBatched;
typedef cublasStatus_t  CUDAAPI tcublasDtrsmBatched(cublasHandle_t, cublasSideMode_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, int, const double *, const double *const *, int, double *const *, int, int);
extern tcublasDtrsmBatched *cublasDtrsmBatched;
typedef cublasStatus_t  CUDAAPI tcublasCtrsmBatched(cublasHandle_t, cublasSideMode_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, int, const cuComplex *, const cuComplex *const *, int, cuComplex *const *, int, int);
extern tcublasCtrsmBatched *cublasCtrsmBatched;
typedef cublasStatus_t  CUDAAPI tcublasZtrsmBatched(cublasHandle_t, cublasSideMode_t, cublasFillMode_t, cublasOperation_t, cublasDiagType_t, int, int, const cuDoubleComplex *, const cuDoubleComplex *const *, int, cuDoubleComplex *const *, int, int);
extern tcublasZtrsmBatched *cublasZtrsmBatched;
typedef cublasStatus_t  CUDAAPI tcublasSmatinvBatched(cublasHandle_t, int, const float *const *, int, float *const *, int, int *, int);
extern tcublasSmatinvBatched *cublasSmatinvBatched;
typedef cublasStatus_t  CUDAAPI tcublasDmatinvBatched(cublasHandle_t, int, const double *const *, int, double *const *, int, int *, int);
extern tcublasDmatinvBatched *cublasDmatinvBatched;
typedef cublasStatus_t  CUDAAPI tcublasCmatinvBatched(cublasHandle_t, int, const cuComplex *const *, int, cuComplex *const *, int, int *, int);
extern tcublasCmatinvBatched *cublasCmatinvBatched;
typedef cublasStatus_t  CUDAAPI tcublasZmatinvBatched(cublasHandle_t, int, const cuDoubleComplex *const *, int, cuDoubleComplex *const *, int, int *, int);
extern tcublasZmatinvBatched *cublasZmatinvBatched;
typedef cublasStatus_t  CUDAAPI tcublasSgeqrfBatched(cublasHandle_t, int, int, float *const *, int, float *const *, int *, int);
extern tcublasSgeqrfBatched *cublasSgeqrfBatched;
typedef cublasStatus_t  CUDAAPI tcublasDgeqrfBatched(cublasHandle_t, int, int, double *const *, int, double *const *, int *, int);
extern tcublasDgeqrfBatched *cublasDgeqrfBatched;
typedef cublasStatus_t  CUDAAPI tcublasCgeqrfBatched(cublasHandle_t, int, int, cuComplex *const *, int, cuComplex *const *, int *, int);
extern tcublasCgeqrfBatched *cublasCgeqrfBatched;
typedef cublasStatus_t  CUDAAPI tcublasZgeqrfBatched(cublasHandle_t, int, int, cuDoubleComplex *const *, int, cuDoubleComplex *const *, int *, int);
extern tcublasZgeqrfBatched *cublasZgeqrfBatched;
typedef cublasStatus_t  CUDAAPI tcublasSgelsBatched(cublasHandle_t, cublasOperation_t, int, int, int, float *const *, int, float *const *, int, int *, int *, int);
extern tcublasSgelsBatched *cublasSgelsBatched;
typedef cublasStatus_t  CUDAAPI tcublasDgelsBatched(cublasHandle_t, cublasOperation_t, int, int, int, double *const *, int, double *const *, int, int *, int *, int);
extern tcublasDgelsBatched *cublasDgelsBatched;
typedef cublasStatus_t  CUDAAPI tcublasCgelsBatched(cublasHandle_t, cublasOperation_t, int, int, int, cuComplex *const *, int, cuComplex *const *, int, int *, int *, int);
extern tcublasCgelsBatched *cublasCgelsBatched;
typedef cublasStatus_t  CUDAAPI tcublasZgelsBatched(cublasHandle_t, cublasOperation_t, int, int, int, cuDoubleComplex *const *, int, cuDoubleComplex *const *, int, int *, int *, int);
extern tcublasZgelsBatched *cublasZgelsBatched;
typedef cublasStatus_t  CUDAAPI tcublasSdgmm(cublasHandle_t, cublasSideMode_t, int, int, const float *, int, const float *, int, float *, int);
extern tcublasSdgmm *cublasSdgmm;
typedef cublasStatus_t  CUDAAPI tcublasDdgmm(cublasHandle_t, cublasSideMode_t, int, int, const double *, int, const double *, int, double *, int);
extern tcublasDdgmm *cublasDdgmm;
typedef cublasStatus_t  CUDAAPI tcublasCdgmm(cublasHandle_t, cublasSideMode_t, int, int, const cuComplex *, int, const cuComplex *, int, cuComplex *, int);
extern tcublasCdgmm *cublasCdgmm;
typedef cublasStatus_t  CUDAAPI tcublasZdgmm(cublasHandle_t, cublasSideMode_t, int, int, const cuDoubleComplex *, int, const cuDoubleComplex *, int, cuDoubleComplex *, int);
extern tcublasZdgmm *cublasZdgmm;
typedef cublasStatus_t  CUDAAPI tcublasStpttr(cublasHandle_t, cublasFillMode_t, int, const float *, float *, int);
extern tcublasStpttr *cublasStpttr;
typedef cublasStatus_t  CUDAAPI tcublasDtpttr(cublasHandle_t, cublasFillMode_t, int, const double *, double *, int);
extern tcublasDtpttr *cublasDtpttr;
typedef cublasStatus_t  CUDAAPI tcublasCtpttr(cublasHandle_t, cublasFillMode_t, int, const cuComplex *, cuComplex *, int);
extern tcublasCtpttr *cublasCtpttr;
typedef cublasStatus_t  CUDAAPI tcublasZtpttr(cublasHandle_t, cublasFillMode_t, int, const cuDoubleComplex *, cuDoubleComplex *, int);
extern tcublasZtpttr *cublasZtpttr;
typedef cublasStatus_t  CUDAAPI tcublasStrttp(cublasHandle_t, cublasFillMode_t, int, const float *, int, float *);
extern tcublasStrttp *cublasStrttp;
typedef cublasStatus_t  CUDAAPI tcublasDtrttp(cublasHandle_t, cublasFillMode_t, int, const double *, int, double *);
extern tcublasDtrttp *cublasDtrttp;
typedef cublasStatus_t  CUDAAPI tcublasCtrttp(cublasHandle_t, cublasFillMode_t, int, const cuComplex *, int, cuComplex *);
extern tcublasCtrttp *cublasCtrttp;
typedef cublasStatus_t  CUDAAPI tcublasZtrttp(cublasHandle_t, cublasFillMode_t, int, const cuDoubleComplex *, int, cuDoubleComplex *);
extern tcublasZtrttp *cublasZtrttp;
extern int cuewInitCUBLAS(void);


#ifdef __cplusplus
}
#endif
#endif /* CUEW_CUBLAS_H_ */
