

#ifdef _MSC_VER
#  if _MSC_VER < 1900
#    define snprintf _snprintf
#  endif
#  define popen _popen
#  define pclose _pclose
#  define _CRT_SECURE_NO_WARNINGS
#endif
#include "cuew.h"
#include "cuew_cusparse.h"
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>


#ifdef _WIN32
#  define WIN32_LEAN_AND_MEAN
#  define VC_EXTRALEAN
#  include <windows.h>


/* Utility macros. */

typedef HMODULE DynamicLibrary;

#  define dynamic_library_open(path)         LoadLibraryA(path)
#  define dynamic_library_close(lib)         FreeLibrary(lib)
#  define dynamic_library_find(lib, symbol)  GetProcAddress(lib, symbol)
#else
#  include <dlfcn.h>

typedef void* DynamicLibrary;

#  define dynamic_library_open(path)         dlopen(path, RTLD_NOW)
#  define dynamic_library_close(lib)         dlclose(lib)
#  define dynamic_library_find(lib, symbol)  dlsym(lib, symbol)
#endif

/*
#define CUEW_IMPL_LIBRARY_FIND_CHECKED(lib, name)         name = (t##name *)dynamic_library_find(lib, #name);         assert(name);
*/

#define CUEW_IMPL_LIBRARY_FIND(lib, name)         name = (t##name *)dynamic_library_find(lib, #name);


static DynamicLibrary dynamic_library_open_find(const char **paths) {
  int i = 0;
  while (paths[i] != NULL) {
      DynamicLibrary lib = dynamic_library_open(paths[i]);
      if (lib != NULL) {
        return lib;
      }
      ++i;
  }
  return NULL;
}

/*#define CUSPARSE_LIBRARY_FIND_CHECKED(name) CUEW_IMPL_LIBRARY_FIND_CHECKED(cusparse_lib, name)*/
#define CUSPARSE_LIBRARY_FIND(name) CUEW_IMPL_LIBRARY_FIND(cusparse_lib, name)
static DynamicLibrary cusparse_lib;

static void cuewExitCUSPARSE(void) {
  if (cusparse_lib != NULL) {
    /* ignore errors */
    dynamic_library_close(cusparse_lib);
    cusparse_lib = NULL;
  }
}

tcusparseCreate *cusparseCreate;
tcusparseDestroy *cusparseDestroy;
tcusparseGetVersion *cusparseGetVersion;
tcusparseGetProperty *cusparseGetProperty;
tcusparseGetErrorName *cusparseGetErrorName;
tcusparseGetErrorString *cusparseGetErrorString;
tcusparseSetStream *cusparseSetStream;
tcusparseGetStream *cusparseGetStream;
tcusparseGetPointerMode *cusparseGetPointerMode;
tcusparseSetPointerMode *cusparseSetPointerMode;
tcusparseLoggerSetCallback *cusparseLoggerSetCallback;
tcusparseLoggerSetFile *cusparseLoggerSetFile;
tcusparseLoggerOpenFile *cusparseLoggerOpenFile;
tcusparseLoggerSetLevel *cusparseLoggerSetLevel;
tcusparseLoggerSetMask *cusparseLoggerSetMask;
tcusparseLoggerForceDisable *cusparseLoggerForceDisable;
tcusparseCreateMatDescr *cusparseCreateMatDescr;
tcusparseDestroyMatDescr *cusparseDestroyMatDescr;
tcusparseCopyMatDescr *cusparseCopyMatDescr;
tcusparseSetMatType *cusparseSetMatType;
tcusparseGetMatType *cusparseGetMatType;
tcusparseSetMatFillMode *cusparseSetMatFillMode;
tcusparseGetMatFillMode *cusparseGetMatFillMode;
tcusparseSetMatDiagType *cusparseSetMatDiagType;
tcusparseGetMatDiagType *cusparseGetMatDiagType;
tcusparseSetMatIndexBase *cusparseSetMatIndexBase;
tcusparseGetMatIndexBase *cusparseGetMatIndexBase;
tcusparseCreateCsrsv2Info *cusparseCreateCsrsv2Info;
tcusparseDestroyCsrsv2Info *cusparseDestroyCsrsv2Info;
tcusparseCreateCsric02Info *cusparseCreateCsric02Info;
tcusparseDestroyCsric02Info *cusparseDestroyCsric02Info;
tcusparseCreateBsric02Info *cusparseCreateBsric02Info;
tcusparseDestroyBsric02Info *cusparseDestroyBsric02Info;
tcusparseCreateCsrilu02Info *cusparseCreateCsrilu02Info;
tcusparseDestroyCsrilu02Info *cusparseDestroyCsrilu02Info;
tcusparseCreateBsrilu02Info *cusparseCreateBsrilu02Info;
tcusparseDestroyBsrilu02Info *cusparseDestroyBsrilu02Info;
tcusparseCreateBsrsv2Info *cusparseCreateBsrsv2Info;
tcusparseDestroyBsrsv2Info *cusparseDestroyBsrsv2Info;
tcusparseCreateBsrsm2Info *cusparseCreateBsrsm2Info;
tcusparseDestroyBsrsm2Info *cusparseDestroyBsrsm2Info;
tcusparseCreateCsru2csrInfo *cusparseCreateCsru2csrInfo;
tcusparseDestroyCsru2csrInfo *cusparseDestroyCsru2csrInfo;
tcusparseCreateColorInfo *cusparseCreateColorInfo;
tcusparseDestroyColorInfo *cusparseDestroyColorInfo;
tcusparseSetColorAlgs *cusparseSetColorAlgs;
tcusparseGetColorAlgs *cusparseGetColorAlgs;
tcusparseCreatePruneInfo *cusparseCreatePruneInfo;
tcusparseDestroyPruneInfo *cusparseDestroyPruneInfo;
tcusparseSaxpyi *cusparseSaxpyi;
tcusparseDaxpyi *cusparseDaxpyi;
tcusparseCaxpyi *cusparseCaxpyi;
tcusparseZaxpyi *cusparseZaxpyi;
tcusparseSgthr *cusparseSgthr;
tcusparseDgthr *cusparseDgthr;
tcusparseCgthr *cusparseCgthr;
tcusparseZgthr *cusparseZgthr;
tcusparseSgthrz *cusparseSgthrz;
tcusparseDgthrz *cusparseDgthrz;
tcusparseCgthrz *cusparseCgthrz;
tcusparseZgthrz *cusparseZgthrz;
tcusparseSsctr *cusparseSsctr;
tcusparseDsctr *cusparseDsctr;
tcusparseCsctr *cusparseCsctr;
tcusparseZsctr *cusparseZsctr;
tcusparseSroti *cusparseSroti;
tcusparseDroti *cusparseDroti;
tcusparseSgemvi *cusparseSgemvi;
tcusparseSgemvi_bufferSize *cusparseSgemvi_bufferSize;
tcusparseDgemvi *cusparseDgemvi;
tcusparseDgemvi_bufferSize *cusparseDgemvi_bufferSize;
tcusparseCgemvi *cusparseCgemvi;
tcusparseCgemvi_bufferSize *cusparseCgemvi_bufferSize;
tcusparseZgemvi *cusparseZgemvi;
tcusparseZgemvi_bufferSize *cusparseZgemvi_bufferSize;
tcusparseCsrmvEx_bufferSize *cusparseCsrmvEx_bufferSize;
tcusparseCsrmvEx *cusparseCsrmvEx;
tcusparseSbsrmv *cusparseSbsrmv;
tcusparseDbsrmv *cusparseDbsrmv;
tcusparseCbsrmv *cusparseCbsrmv;
tcusparseZbsrmv *cusparseZbsrmv;
tcusparseSbsrxmv *cusparseSbsrxmv;
tcusparseDbsrxmv *cusparseDbsrxmv;
tcusparseCbsrxmv *cusparseCbsrxmv;
tcusparseZbsrxmv *cusparseZbsrxmv;
tcusparseXcsrsv2_zeroPivot *cusparseXcsrsv2_zeroPivot;
tcusparseScsrsv2_bufferSize *cusparseScsrsv2_bufferSize;
tcusparseDcsrsv2_bufferSize *cusparseDcsrsv2_bufferSize;
tcusparseCcsrsv2_bufferSize *cusparseCcsrsv2_bufferSize;
tcusparseZcsrsv2_bufferSize *cusparseZcsrsv2_bufferSize;
tcusparseScsrsv2_bufferSizeExt *cusparseScsrsv2_bufferSizeExt;
tcusparseDcsrsv2_bufferSizeExt *cusparseDcsrsv2_bufferSizeExt;
tcusparseCcsrsv2_bufferSizeExt *cusparseCcsrsv2_bufferSizeExt;
tcusparseZcsrsv2_bufferSizeExt *cusparseZcsrsv2_bufferSizeExt;
tcusparseScsrsv2_analysis *cusparseScsrsv2_analysis;
tcusparseDcsrsv2_analysis *cusparseDcsrsv2_analysis;
tcusparseCcsrsv2_analysis *cusparseCcsrsv2_analysis;
tcusparseZcsrsv2_analysis *cusparseZcsrsv2_analysis;
tcusparseScsrsv2_solve *cusparseScsrsv2_solve;
tcusparseDcsrsv2_solve *cusparseDcsrsv2_solve;
tcusparseCcsrsv2_solve *cusparseCcsrsv2_solve;
tcusparseZcsrsv2_solve *cusparseZcsrsv2_solve;
tcusparseXbsrsv2_zeroPivot *cusparseXbsrsv2_zeroPivot;
tcusparseSbsrsv2_bufferSize *cusparseSbsrsv2_bufferSize;
tcusparseDbsrsv2_bufferSize *cusparseDbsrsv2_bufferSize;
tcusparseCbsrsv2_bufferSize *cusparseCbsrsv2_bufferSize;
tcusparseZbsrsv2_bufferSize *cusparseZbsrsv2_bufferSize;
tcusparseSbsrsv2_bufferSizeExt *cusparseSbsrsv2_bufferSizeExt;
tcusparseDbsrsv2_bufferSizeExt *cusparseDbsrsv2_bufferSizeExt;
tcusparseCbsrsv2_bufferSizeExt *cusparseCbsrsv2_bufferSizeExt;
tcusparseZbsrsv2_bufferSizeExt *cusparseZbsrsv2_bufferSizeExt;
tcusparseSbsrsv2_analysis *cusparseSbsrsv2_analysis;
tcusparseDbsrsv2_analysis *cusparseDbsrsv2_analysis;
tcusparseCbsrsv2_analysis *cusparseCbsrsv2_analysis;
tcusparseZbsrsv2_analysis *cusparseZbsrsv2_analysis;
tcusparseSbsrsv2_solve *cusparseSbsrsv2_solve;
tcusparseDbsrsv2_solve *cusparseDbsrsv2_solve;
tcusparseCbsrsv2_solve *cusparseCbsrsv2_solve;
tcusparseZbsrsv2_solve *cusparseZbsrsv2_solve;
tcusparseSbsrmm *cusparseSbsrmm;
tcusparseDbsrmm *cusparseDbsrmm;
tcusparseCbsrmm *cusparseCbsrmm;
tcusparseZbsrmm *cusparseZbsrmm;
tcusparseSgemmi *cusparseSgemmi;
tcusparseDgemmi *cusparseDgemmi;
tcusparseCgemmi *cusparseCgemmi;
tcusparseZgemmi *cusparseZgemmi;
tcusparseCreateCsrsm2Info *cusparseCreateCsrsm2Info;
tcusparseDestroyCsrsm2Info *cusparseDestroyCsrsm2Info;
tcusparseXcsrsm2_zeroPivot *cusparseXcsrsm2_zeroPivot;
tcusparseScsrsm2_bufferSizeExt *cusparseScsrsm2_bufferSizeExt;
tcusparseDcsrsm2_bufferSizeExt *cusparseDcsrsm2_bufferSizeExt;
tcusparseCcsrsm2_bufferSizeExt *cusparseCcsrsm2_bufferSizeExt;
tcusparseZcsrsm2_bufferSizeExt *cusparseZcsrsm2_bufferSizeExt;
tcusparseScsrsm2_analysis *cusparseScsrsm2_analysis;
tcusparseDcsrsm2_analysis *cusparseDcsrsm2_analysis;
tcusparseCcsrsm2_analysis *cusparseCcsrsm2_analysis;
tcusparseZcsrsm2_analysis *cusparseZcsrsm2_analysis;
tcusparseScsrsm2_solve *cusparseScsrsm2_solve;
tcusparseDcsrsm2_solve *cusparseDcsrsm2_solve;
tcusparseCcsrsm2_solve *cusparseCcsrsm2_solve;
tcusparseZcsrsm2_solve *cusparseZcsrsm2_solve;
tcusparseXbsrsm2_zeroPivot *cusparseXbsrsm2_zeroPivot;
tcusparseSbsrsm2_bufferSize *cusparseSbsrsm2_bufferSize;
tcusparseDbsrsm2_bufferSize *cusparseDbsrsm2_bufferSize;
tcusparseCbsrsm2_bufferSize *cusparseCbsrsm2_bufferSize;
tcusparseZbsrsm2_bufferSize *cusparseZbsrsm2_bufferSize;
tcusparseSbsrsm2_bufferSizeExt *cusparseSbsrsm2_bufferSizeExt;
tcusparseDbsrsm2_bufferSizeExt *cusparseDbsrsm2_bufferSizeExt;
tcusparseCbsrsm2_bufferSizeExt *cusparseCbsrsm2_bufferSizeExt;
tcusparseZbsrsm2_bufferSizeExt *cusparseZbsrsm2_bufferSizeExt;
tcusparseSbsrsm2_analysis *cusparseSbsrsm2_analysis;
tcusparseDbsrsm2_analysis *cusparseDbsrsm2_analysis;
tcusparseCbsrsm2_analysis *cusparseCbsrsm2_analysis;
tcusparseZbsrsm2_analysis *cusparseZbsrsm2_analysis;
tcusparseSbsrsm2_solve *cusparseSbsrsm2_solve;
tcusparseDbsrsm2_solve *cusparseDbsrsm2_solve;
tcusparseCbsrsm2_solve *cusparseCbsrsm2_solve;
tcusparseZbsrsm2_solve *cusparseZbsrsm2_solve;
tcusparseScsrilu02_numericBoost *cusparseScsrilu02_numericBoost;
tcusparseDcsrilu02_numericBoost *cusparseDcsrilu02_numericBoost;
tcusparseCcsrilu02_numericBoost *cusparseCcsrilu02_numericBoost;
tcusparseZcsrilu02_numericBoost *cusparseZcsrilu02_numericBoost;
tcusparseXcsrilu02_zeroPivot *cusparseXcsrilu02_zeroPivot;
tcusparseScsrilu02_bufferSize *cusparseScsrilu02_bufferSize;
tcusparseDcsrilu02_bufferSize *cusparseDcsrilu02_bufferSize;
tcusparseCcsrilu02_bufferSize *cusparseCcsrilu02_bufferSize;
tcusparseZcsrilu02_bufferSize *cusparseZcsrilu02_bufferSize;
tcusparseScsrilu02_bufferSizeExt *cusparseScsrilu02_bufferSizeExt;
tcusparseDcsrilu02_bufferSizeExt *cusparseDcsrilu02_bufferSizeExt;
tcusparseCcsrilu02_bufferSizeExt *cusparseCcsrilu02_bufferSizeExt;
tcusparseZcsrilu02_bufferSizeExt *cusparseZcsrilu02_bufferSizeExt;
tcusparseScsrilu02_analysis *cusparseScsrilu02_analysis;
tcusparseDcsrilu02_analysis *cusparseDcsrilu02_analysis;
tcusparseCcsrilu02_analysis *cusparseCcsrilu02_analysis;
tcusparseZcsrilu02_analysis *cusparseZcsrilu02_analysis;
tcusparseScsrilu02 *cusparseScsrilu02;
tcusparseDcsrilu02 *cusparseDcsrilu02;
tcusparseCcsrilu02 *cusparseCcsrilu02;
tcusparseZcsrilu02 *cusparseZcsrilu02;
tcusparseSbsrilu02_numericBoost *cusparseSbsrilu02_numericBoost;
tcusparseDbsrilu02_numericBoost *cusparseDbsrilu02_numericBoost;
tcusparseCbsrilu02_numericBoost *cusparseCbsrilu02_numericBoost;
tcusparseZbsrilu02_numericBoost *cusparseZbsrilu02_numericBoost;
tcusparseXbsrilu02_zeroPivot *cusparseXbsrilu02_zeroPivot;
tcusparseSbsrilu02_bufferSize *cusparseSbsrilu02_bufferSize;
tcusparseDbsrilu02_bufferSize *cusparseDbsrilu02_bufferSize;
tcusparseCbsrilu02_bufferSize *cusparseCbsrilu02_bufferSize;
tcusparseZbsrilu02_bufferSize *cusparseZbsrilu02_bufferSize;
tcusparseSbsrilu02_bufferSizeExt *cusparseSbsrilu02_bufferSizeExt;
tcusparseDbsrilu02_bufferSizeExt *cusparseDbsrilu02_bufferSizeExt;
tcusparseCbsrilu02_bufferSizeExt *cusparseCbsrilu02_bufferSizeExt;
tcusparseZbsrilu02_bufferSizeExt *cusparseZbsrilu02_bufferSizeExt;
tcusparseSbsrilu02_analysis *cusparseSbsrilu02_analysis;
tcusparseDbsrilu02_analysis *cusparseDbsrilu02_analysis;
tcusparseCbsrilu02_analysis *cusparseCbsrilu02_analysis;
tcusparseZbsrilu02_analysis *cusparseZbsrilu02_analysis;
tcusparseSbsrilu02 *cusparseSbsrilu02;
tcusparseDbsrilu02 *cusparseDbsrilu02;
tcusparseCbsrilu02 *cusparseCbsrilu02;
tcusparseZbsrilu02 *cusparseZbsrilu02;
tcusparseXcsric02_zeroPivot *cusparseXcsric02_zeroPivot;
tcusparseScsric02_bufferSize *cusparseScsric02_bufferSize;
tcusparseDcsric02_bufferSize *cusparseDcsric02_bufferSize;
tcusparseCcsric02_bufferSize *cusparseCcsric02_bufferSize;
tcusparseZcsric02_bufferSize *cusparseZcsric02_bufferSize;
tcusparseScsric02_bufferSizeExt *cusparseScsric02_bufferSizeExt;
tcusparseDcsric02_bufferSizeExt *cusparseDcsric02_bufferSizeExt;
tcusparseCcsric02_bufferSizeExt *cusparseCcsric02_bufferSizeExt;
tcusparseZcsric02_bufferSizeExt *cusparseZcsric02_bufferSizeExt;
tcusparseScsric02_analysis *cusparseScsric02_analysis;
tcusparseDcsric02_analysis *cusparseDcsric02_analysis;
tcusparseCcsric02_analysis *cusparseCcsric02_analysis;
tcusparseZcsric02_analysis *cusparseZcsric02_analysis;
tcusparseScsric02 *cusparseScsric02;
tcusparseDcsric02 *cusparseDcsric02;
tcusparseCcsric02 *cusparseCcsric02;
tcusparseZcsric02 *cusparseZcsric02;
tcusparseXbsric02_zeroPivot *cusparseXbsric02_zeroPivot;
tcusparseSbsric02_bufferSize *cusparseSbsric02_bufferSize;
tcusparseDbsric02_bufferSize *cusparseDbsric02_bufferSize;
tcusparseCbsric02_bufferSize *cusparseCbsric02_bufferSize;
tcusparseZbsric02_bufferSize *cusparseZbsric02_bufferSize;
tcusparseSbsric02_bufferSizeExt *cusparseSbsric02_bufferSizeExt;
tcusparseDbsric02_bufferSizeExt *cusparseDbsric02_bufferSizeExt;
tcusparseCbsric02_bufferSizeExt *cusparseCbsric02_bufferSizeExt;
tcusparseZbsric02_bufferSizeExt *cusparseZbsric02_bufferSizeExt;
tcusparseSbsric02_analysis *cusparseSbsric02_analysis;
tcusparseDbsric02_analysis *cusparseDbsric02_analysis;
tcusparseCbsric02_analysis *cusparseCbsric02_analysis;
tcusparseZbsric02_analysis *cusparseZbsric02_analysis;
tcusparseSbsric02 *cusparseSbsric02;
tcusparseDbsric02 *cusparseDbsric02;
tcusparseCbsric02 *cusparseCbsric02;
tcusparseZbsric02 *cusparseZbsric02;
tcusparseSgtsv2_bufferSizeExt *cusparseSgtsv2_bufferSizeExt;
tcusparseDgtsv2_bufferSizeExt *cusparseDgtsv2_bufferSizeExt;
tcusparseCgtsv2_bufferSizeExt *cusparseCgtsv2_bufferSizeExt;
tcusparseZgtsv2_bufferSizeExt *cusparseZgtsv2_bufferSizeExt;
tcusparseSgtsv2 *cusparseSgtsv2;
tcusparseDgtsv2 *cusparseDgtsv2;
tcusparseCgtsv2 *cusparseCgtsv2;
tcusparseZgtsv2 *cusparseZgtsv2;
tcusparseSgtsv2_nopivot_bufferSizeExt *cusparseSgtsv2_nopivot_bufferSizeExt;
tcusparseDgtsv2_nopivot_bufferSizeExt *cusparseDgtsv2_nopivot_bufferSizeExt;
tcusparseCgtsv2_nopivot_bufferSizeExt *cusparseCgtsv2_nopivot_bufferSizeExt;
tcusparseZgtsv2_nopivot_bufferSizeExt *cusparseZgtsv2_nopivot_bufferSizeExt;
tcusparseSgtsv2_nopivot *cusparseSgtsv2_nopivot;
tcusparseDgtsv2_nopivot *cusparseDgtsv2_nopivot;
tcusparseCgtsv2_nopivot *cusparseCgtsv2_nopivot;
tcusparseZgtsv2_nopivot *cusparseZgtsv2_nopivot;
tcusparseSgtsv2StridedBatch_bufferSizeExt *cusparseSgtsv2StridedBatch_bufferSizeExt;
tcusparseDgtsv2StridedBatch_bufferSizeExt *cusparseDgtsv2StridedBatch_bufferSizeExt;
tcusparseCgtsv2StridedBatch_bufferSizeExt *cusparseCgtsv2StridedBatch_bufferSizeExt;
tcusparseZgtsv2StridedBatch_bufferSizeExt *cusparseZgtsv2StridedBatch_bufferSizeExt;
tcusparseSgtsv2StridedBatch *cusparseSgtsv2StridedBatch;
tcusparseDgtsv2StridedBatch *cusparseDgtsv2StridedBatch;
tcusparseCgtsv2StridedBatch *cusparseCgtsv2StridedBatch;
tcusparseZgtsv2StridedBatch *cusparseZgtsv2StridedBatch;
tcusparseSgtsvInterleavedBatch_bufferSizeExt *cusparseSgtsvInterleavedBatch_bufferSizeExt;
tcusparseDgtsvInterleavedBatch_bufferSizeExt *cusparseDgtsvInterleavedBatch_bufferSizeExt;
tcusparseCgtsvInterleavedBatch_bufferSizeExt *cusparseCgtsvInterleavedBatch_bufferSizeExt;
tcusparseZgtsvInterleavedBatch_bufferSizeExt *cusparseZgtsvInterleavedBatch_bufferSizeExt;
tcusparseSgtsvInterleavedBatch *cusparseSgtsvInterleavedBatch;
tcusparseDgtsvInterleavedBatch *cusparseDgtsvInterleavedBatch;
tcusparseCgtsvInterleavedBatch *cusparseCgtsvInterleavedBatch;
tcusparseZgtsvInterleavedBatch *cusparseZgtsvInterleavedBatch;
tcusparseSgpsvInterleavedBatch_bufferSizeExt *cusparseSgpsvInterleavedBatch_bufferSizeExt;
tcusparseDgpsvInterleavedBatch_bufferSizeExt *cusparseDgpsvInterleavedBatch_bufferSizeExt;
tcusparseCgpsvInterleavedBatch_bufferSizeExt *cusparseCgpsvInterleavedBatch_bufferSizeExt;
tcusparseZgpsvInterleavedBatch_bufferSizeExt *cusparseZgpsvInterleavedBatch_bufferSizeExt;
tcusparseSgpsvInterleavedBatch *cusparseSgpsvInterleavedBatch;
tcusparseDgpsvInterleavedBatch *cusparseDgpsvInterleavedBatch;
tcusparseCgpsvInterleavedBatch *cusparseCgpsvInterleavedBatch;
tcusparseZgpsvInterleavedBatch *cusparseZgpsvInterleavedBatch;
tcusparseCreateCsrgemm2Info *cusparseCreateCsrgemm2Info;
tcusparseDestroyCsrgemm2Info *cusparseDestroyCsrgemm2Info;
tcusparseScsrgemm2_bufferSizeExt *cusparseScsrgemm2_bufferSizeExt;
tcusparseDcsrgemm2_bufferSizeExt *cusparseDcsrgemm2_bufferSizeExt;
tcusparseCcsrgemm2_bufferSizeExt *cusparseCcsrgemm2_bufferSizeExt;
tcusparseZcsrgemm2_bufferSizeExt *cusparseZcsrgemm2_bufferSizeExt;
tcusparseXcsrgemm2Nnz *cusparseXcsrgemm2Nnz;
tcusparseScsrgemm2 *cusparseScsrgemm2;
tcusparseDcsrgemm2 *cusparseDcsrgemm2;
tcusparseCcsrgemm2 *cusparseCcsrgemm2;
tcusparseZcsrgemm2 *cusparseZcsrgemm2;
tcusparseScsrgeam2_bufferSizeExt *cusparseScsrgeam2_bufferSizeExt;
tcusparseDcsrgeam2_bufferSizeExt *cusparseDcsrgeam2_bufferSizeExt;
tcusparseCcsrgeam2_bufferSizeExt *cusparseCcsrgeam2_bufferSizeExt;
tcusparseZcsrgeam2_bufferSizeExt *cusparseZcsrgeam2_bufferSizeExt;
tcusparseXcsrgeam2Nnz *cusparseXcsrgeam2Nnz;
tcusparseScsrgeam2 *cusparseScsrgeam2;
tcusparseDcsrgeam2 *cusparseDcsrgeam2;
tcusparseCcsrgeam2 *cusparseCcsrgeam2;
tcusparseZcsrgeam2 *cusparseZcsrgeam2;
tcusparseScsrcolor *cusparseScsrcolor;
tcusparseDcsrcolor *cusparseDcsrcolor;
tcusparseCcsrcolor *cusparseCcsrcolor;
tcusparseZcsrcolor *cusparseZcsrcolor;
tcusparseSnnz *cusparseSnnz;
tcusparseDnnz *cusparseDnnz;
tcusparseCnnz *cusparseCnnz;
tcusparseZnnz *cusparseZnnz;
tcusparseSnnz_compress *cusparseSnnz_compress;
tcusparseDnnz_compress *cusparseDnnz_compress;
tcusparseCnnz_compress *cusparseCnnz_compress;
tcusparseZnnz_compress *cusparseZnnz_compress;
tcusparseScsr2csr_compress *cusparseScsr2csr_compress;
tcusparseDcsr2csr_compress *cusparseDcsr2csr_compress;
tcusparseCcsr2csr_compress *cusparseCcsr2csr_compress;
tcusparseZcsr2csr_compress *cusparseZcsr2csr_compress;
tcusparseSdense2csr *cusparseSdense2csr;
tcusparseDdense2csr *cusparseDdense2csr;
tcusparseCdense2csr *cusparseCdense2csr;
tcusparseZdense2csr *cusparseZdense2csr;
tcusparseScsr2dense *cusparseScsr2dense;
tcusparseDcsr2dense *cusparseDcsr2dense;
tcusparseCcsr2dense *cusparseCcsr2dense;
tcusparseZcsr2dense *cusparseZcsr2dense;
tcusparseSdense2csc *cusparseSdense2csc;
tcusparseDdense2csc *cusparseDdense2csc;
tcusparseCdense2csc *cusparseCdense2csc;
tcusparseZdense2csc *cusparseZdense2csc;
tcusparseScsc2dense *cusparseScsc2dense;
tcusparseDcsc2dense *cusparseDcsc2dense;
tcusparseCcsc2dense *cusparseCcsc2dense;
tcusparseZcsc2dense *cusparseZcsc2dense;
tcusparseXcoo2csr *cusparseXcoo2csr;
tcusparseXcsr2coo *cusparseXcsr2coo;
tcusparseXcsr2bsrNnz *cusparseXcsr2bsrNnz;
tcusparseScsr2bsr *cusparseScsr2bsr;
tcusparseDcsr2bsr *cusparseDcsr2bsr;
tcusparseCcsr2bsr *cusparseCcsr2bsr;
tcusparseZcsr2bsr *cusparseZcsr2bsr;
tcusparseSbsr2csr *cusparseSbsr2csr;
tcusparseDbsr2csr *cusparseDbsr2csr;
tcusparseCbsr2csr *cusparseCbsr2csr;
tcusparseZbsr2csr *cusparseZbsr2csr;
tcusparseSgebsr2gebsc_bufferSize *cusparseSgebsr2gebsc_bufferSize;
tcusparseDgebsr2gebsc_bufferSize *cusparseDgebsr2gebsc_bufferSize;
tcusparseCgebsr2gebsc_bufferSize *cusparseCgebsr2gebsc_bufferSize;
tcusparseZgebsr2gebsc_bufferSize *cusparseZgebsr2gebsc_bufferSize;
tcusparseSgebsr2gebsc_bufferSizeExt *cusparseSgebsr2gebsc_bufferSizeExt;
tcusparseDgebsr2gebsc_bufferSizeExt *cusparseDgebsr2gebsc_bufferSizeExt;
tcusparseCgebsr2gebsc_bufferSizeExt *cusparseCgebsr2gebsc_bufferSizeExt;
tcusparseZgebsr2gebsc_bufferSizeExt *cusparseZgebsr2gebsc_bufferSizeExt;
tcusparseSgebsr2gebsc *cusparseSgebsr2gebsc;
tcusparseDgebsr2gebsc *cusparseDgebsr2gebsc;
tcusparseCgebsr2gebsc *cusparseCgebsr2gebsc;
tcusparseZgebsr2gebsc *cusparseZgebsr2gebsc;
tcusparseXgebsr2csr *cusparseXgebsr2csr;
tcusparseSgebsr2csr *cusparseSgebsr2csr;
tcusparseDgebsr2csr *cusparseDgebsr2csr;
tcusparseCgebsr2csr *cusparseCgebsr2csr;
tcusparseZgebsr2csr *cusparseZgebsr2csr;
tcusparseScsr2gebsr_bufferSize *cusparseScsr2gebsr_bufferSize;
tcusparseDcsr2gebsr_bufferSize *cusparseDcsr2gebsr_bufferSize;
tcusparseCcsr2gebsr_bufferSize *cusparseCcsr2gebsr_bufferSize;
tcusparseZcsr2gebsr_bufferSize *cusparseZcsr2gebsr_bufferSize;
tcusparseScsr2gebsr_bufferSizeExt *cusparseScsr2gebsr_bufferSizeExt;
tcusparseDcsr2gebsr_bufferSizeExt *cusparseDcsr2gebsr_bufferSizeExt;
tcusparseCcsr2gebsr_bufferSizeExt *cusparseCcsr2gebsr_bufferSizeExt;
tcusparseZcsr2gebsr_bufferSizeExt *cusparseZcsr2gebsr_bufferSizeExt;
tcusparseXcsr2gebsrNnz *cusparseXcsr2gebsrNnz;
tcusparseScsr2gebsr *cusparseScsr2gebsr;
tcusparseDcsr2gebsr *cusparseDcsr2gebsr;
tcusparseCcsr2gebsr *cusparseCcsr2gebsr;
tcusparseZcsr2gebsr *cusparseZcsr2gebsr;
tcusparseSgebsr2gebsr_bufferSize *cusparseSgebsr2gebsr_bufferSize;
tcusparseDgebsr2gebsr_bufferSize *cusparseDgebsr2gebsr_bufferSize;
tcusparseCgebsr2gebsr_bufferSize *cusparseCgebsr2gebsr_bufferSize;
tcusparseZgebsr2gebsr_bufferSize *cusparseZgebsr2gebsr_bufferSize;
tcusparseSgebsr2gebsr_bufferSizeExt *cusparseSgebsr2gebsr_bufferSizeExt;
tcusparseDgebsr2gebsr_bufferSizeExt *cusparseDgebsr2gebsr_bufferSizeExt;
tcusparseCgebsr2gebsr_bufferSizeExt *cusparseCgebsr2gebsr_bufferSizeExt;
tcusparseZgebsr2gebsr_bufferSizeExt *cusparseZgebsr2gebsr_bufferSizeExt;
tcusparseXgebsr2gebsrNnz *cusparseXgebsr2gebsrNnz;
tcusparseSgebsr2gebsr *cusparseSgebsr2gebsr;
tcusparseDgebsr2gebsr *cusparseDgebsr2gebsr;
tcusparseCgebsr2gebsr *cusparseCgebsr2gebsr;
tcusparseZgebsr2gebsr *cusparseZgebsr2gebsr;
tcusparseCreateIdentityPermutation *cusparseCreateIdentityPermutation;
tcusparseXcoosort_bufferSizeExt *cusparseXcoosort_bufferSizeExt;
tcusparseXcoosortByRow *cusparseXcoosortByRow;
tcusparseXcoosortByColumn *cusparseXcoosortByColumn;
tcusparseXcsrsort_bufferSizeExt *cusparseXcsrsort_bufferSizeExt;
tcusparseXcsrsort *cusparseXcsrsort;
tcusparseXcscsort_bufferSizeExt *cusparseXcscsort_bufferSizeExt;
tcusparseXcscsort *cusparseXcscsort;
tcusparseScsru2csr_bufferSizeExt *cusparseScsru2csr_bufferSizeExt;
tcusparseDcsru2csr_bufferSizeExt *cusparseDcsru2csr_bufferSizeExt;
tcusparseCcsru2csr_bufferSizeExt *cusparseCcsru2csr_bufferSizeExt;
tcusparseZcsru2csr_bufferSizeExt *cusparseZcsru2csr_bufferSizeExt;
tcusparseScsru2csr *cusparseScsru2csr;
tcusparseDcsru2csr *cusparseDcsru2csr;
tcusparseCcsru2csr *cusparseCcsru2csr;
tcusparseZcsru2csr *cusparseZcsru2csr;
tcusparseScsr2csru *cusparseScsr2csru;
tcusparseDcsr2csru *cusparseDcsr2csru;
tcusparseCcsr2csru *cusparseCcsr2csru;
tcusparseZcsr2csru *cusparseZcsr2csru;
tcusparseSpruneDense2csr_bufferSizeExt *cusparseSpruneDense2csr_bufferSizeExt;
tcusparseDpruneDense2csr_bufferSizeExt *cusparseDpruneDense2csr_bufferSizeExt;
tcusparseSpruneDense2csrNnz *cusparseSpruneDense2csrNnz;
tcusparseDpruneDense2csrNnz *cusparseDpruneDense2csrNnz;
tcusparseSpruneDense2csr *cusparseSpruneDense2csr;
tcusparseDpruneDense2csr *cusparseDpruneDense2csr;
tcusparseSpruneCsr2csr_bufferSizeExt *cusparseSpruneCsr2csr_bufferSizeExt;
tcusparseDpruneCsr2csr_bufferSizeExt *cusparseDpruneCsr2csr_bufferSizeExt;
tcusparseSpruneCsr2csrNnz *cusparseSpruneCsr2csrNnz;
tcusparseDpruneCsr2csrNnz *cusparseDpruneCsr2csrNnz;
tcusparseSpruneCsr2csr *cusparseSpruneCsr2csr;
tcusparseDpruneCsr2csr *cusparseDpruneCsr2csr;
tcusparseSpruneDense2csrByPercentage_bufferSizeExt *cusparseSpruneDense2csrByPercentage_bufferSizeExt;
tcusparseDpruneDense2csrByPercentage_bufferSizeExt *cusparseDpruneDense2csrByPercentage_bufferSizeExt;
tcusparseSpruneDense2csrNnzByPercentage *cusparseSpruneDense2csrNnzByPercentage;
tcusparseDpruneDense2csrNnzByPercentage *cusparseDpruneDense2csrNnzByPercentage;
tcusparseSpruneDense2csrByPercentage *cusparseSpruneDense2csrByPercentage;
tcusparseDpruneDense2csrByPercentage *cusparseDpruneDense2csrByPercentage;
tcusparseSpruneCsr2csrByPercentage_bufferSizeExt *cusparseSpruneCsr2csrByPercentage_bufferSizeExt;
tcusparseDpruneCsr2csrByPercentage_bufferSizeExt *cusparseDpruneCsr2csrByPercentage_bufferSizeExt;
tcusparseSpruneCsr2csrNnzByPercentage *cusparseSpruneCsr2csrNnzByPercentage;
tcusparseDpruneCsr2csrNnzByPercentage *cusparseDpruneCsr2csrNnzByPercentage;
tcusparseSpruneCsr2csrByPercentage *cusparseSpruneCsr2csrByPercentage;
tcusparseDpruneCsr2csrByPercentage *cusparseDpruneCsr2csrByPercentage;
tcusparseCsr2cscEx2 *cusparseCsr2cscEx2;
tcusparseCsr2cscEx2_bufferSize *cusparseCsr2cscEx2_bufferSize;
tcusparseCreateSpVec *cusparseCreateSpVec;
tcusparseDestroySpVec *cusparseDestroySpVec;
tcusparseSpVecGet *cusparseSpVecGet;
tcusparseSpVecGetIndexBase *cusparseSpVecGetIndexBase;
tcusparseSpVecGetValues *cusparseSpVecGetValues;
tcusparseSpVecSetValues *cusparseSpVecSetValues;
tcusparseCreateDnVec *cusparseCreateDnVec;
tcusparseDestroyDnVec *cusparseDestroyDnVec;
tcusparseDnVecGet *cusparseDnVecGet;
tcusparseDnVecGetValues *cusparseDnVecGetValues;
tcusparseDnVecSetValues *cusparseDnVecSetValues;
tcusparseDestroySpMat *cusparseDestroySpMat;
tcusparseSpMatGetFormat *cusparseSpMatGetFormat;
tcusparseSpMatGetIndexBase *cusparseSpMatGetIndexBase;
tcusparseSpMatGetValues *cusparseSpMatGetValues;
tcusparseSpMatSetValues *cusparseSpMatSetValues;
tcusparseSpMatGetSize *cusparseSpMatGetSize;
tcusparseSpMatSetStridedBatch *cusparseSpMatSetStridedBatch;
tcusparseSpMatGetStridedBatch *cusparseSpMatGetStridedBatch;
tcusparseCooSetStridedBatch *cusparseCooSetStridedBatch;
tcusparseCsrSetStridedBatch *cusparseCsrSetStridedBatch;
tcusparseSpMatGetAttribute *cusparseSpMatGetAttribute;
tcusparseSpMatSetAttribute *cusparseSpMatSetAttribute;
tcusparseCreateCsr *cusparseCreateCsr;
tcusparseCreateCsc *cusparseCreateCsc;
tcusparseCsrGet *cusparseCsrGet;
tcusparseCsrSetPointers *cusparseCsrSetPointers;
tcusparseCscSetPointers *cusparseCscSetPointers;
tcusparseCreateCoo *cusparseCreateCoo;
tcusparseCreateCooAoS *cusparseCreateCooAoS;
tcusparseCooGet *cusparseCooGet;
tcusparseCooAoSGet *cusparseCooAoSGet;
tcusparseCooSetPointers *cusparseCooSetPointers;
tcusparseCreateBlockedEll *cusparseCreateBlockedEll;
tcusparseBlockedEllGet *cusparseBlockedEllGet;
tcusparseCreateDnMat *cusparseCreateDnMat;
tcusparseDestroyDnMat *cusparseDestroyDnMat;
tcusparseDnMatGet *cusparseDnMatGet;
tcusparseDnMatGetValues *cusparseDnMatGetValues;
tcusparseDnMatSetValues *cusparseDnMatSetValues;
tcusparseDnMatSetStridedBatch *cusparseDnMatSetStridedBatch;
tcusparseDnMatGetStridedBatch *cusparseDnMatGetStridedBatch;
tcusparseAxpby *cusparseAxpby;
tcusparseGather *cusparseGather;
tcusparseScatter *cusparseScatter;
tcusparseRot *cusparseRot;
tcusparseSpVV_bufferSize *cusparseSpVV_bufferSize;
tcusparseSpVV *cusparseSpVV;
tcusparseSparseToDense_bufferSize *cusparseSparseToDense_bufferSize;
tcusparseSparseToDense *cusparseSparseToDense;
tcusparseDenseToSparse_bufferSize *cusparseDenseToSparse_bufferSize;
tcusparseDenseToSparse_analysis *cusparseDenseToSparse_analysis;
tcusparseDenseToSparse_convert *cusparseDenseToSparse_convert;
tcusparseSpMV *cusparseSpMV;
tcusparseSpMV_bufferSize *cusparseSpMV_bufferSize;
tcusparseSpSV_createDescr *cusparseSpSV_createDescr;
tcusparseSpSV_destroyDescr *cusparseSpSV_destroyDescr;
tcusparseSpSV_bufferSize *cusparseSpSV_bufferSize;
tcusparseSpSV_analysis *cusparseSpSV_analysis;
tcusparseSpSV_solve *cusparseSpSV_solve;
tcusparseSpSM_createDescr *cusparseSpSM_createDescr;
tcusparseSpSM_destroyDescr *cusparseSpSM_destroyDescr;
tcusparseSpSM_bufferSize *cusparseSpSM_bufferSize;
tcusparseSpSM_analysis *cusparseSpSM_analysis;
tcusparseSpSM_solve *cusparseSpSM_solve;
tcusparseSpMM_bufferSize *cusparseSpMM_bufferSize;
tcusparseSpMM_preprocess *cusparseSpMM_preprocess;
tcusparseSpMM *cusparseSpMM;
tcusparseSpGEMM_createDescr *cusparseSpGEMM_createDescr;
tcusparseSpGEMM_destroyDescr *cusparseSpGEMM_destroyDescr;
tcusparseSpGEMM_workEstimation *cusparseSpGEMM_workEstimation;
tcusparseSpGEMM_compute *cusparseSpGEMM_compute;
tcusparseSpGEMM_copy *cusparseSpGEMM_copy;
tcusparseSpGEMMreuse_workEstimation *cusparseSpGEMMreuse_workEstimation;
tcusparseSpGEMMreuse_nnz *cusparseSpGEMMreuse_nnz;
tcusparseSpGEMMreuse_copy *cusparseSpGEMMreuse_copy;
tcusparseSpGEMMreuse_compute *cusparseSpGEMMreuse_compute;
tcusparseConstrainedGeMM *cusparseConstrainedGeMM;
tcusparseConstrainedGeMM_bufferSize *cusparseConstrainedGeMM_bufferSize;
tcusparseSDDMM_bufferSize *cusparseSDDMM_bufferSize;
tcusparseSDDMM_preprocess *cusparseSDDMM_preprocess;
tcusparseSDDMM *cusparseSDDMM;
tcusparseSpMMOp_createPlan *cusparseSpMMOp_createPlan;
tcusparseSpMMOp *cusparseSpMMOp;
tcusparseSpMMOp_destroyPlan *cusparseSpMMOp_destroyPlan;

int cuewInitCUSPARSE() {

#ifdef _WIN32
  const char *paths[] = {   "cusparse.dll",
NULL};
#else /* linux */
  const char *paths[] = {   "libcusparse.so",
   "/usr/local/cuda/lib64/libcusparse.so",
NULL};
#endif


  static int initialized = 0;
  static int result = 0;
  int error;

  if (initialized) {
    return result;
  }

  initialized = 1;
  error = atexit(cuewExitCUSPARSE);

  if (error) {
    result = -2;
    return result;
  }
  cusparse_lib = dynamic_library_open_find(paths);
  if (cusparse_lib == NULL) { result = -1; return result; }

  CUSPARSE_LIBRARY_FIND(cusparseCreate)
  CUSPARSE_LIBRARY_FIND(cusparseDestroy)
  CUSPARSE_LIBRARY_FIND(cusparseGetVersion)
  CUSPARSE_LIBRARY_FIND(cusparseGetProperty)
  CUSPARSE_LIBRARY_FIND(cusparseGetErrorName)
  CUSPARSE_LIBRARY_FIND(cusparseGetErrorString)
  CUSPARSE_LIBRARY_FIND(cusparseSetStream)
  CUSPARSE_LIBRARY_FIND(cusparseGetStream)
  CUSPARSE_LIBRARY_FIND(cusparseGetPointerMode)
  CUSPARSE_LIBRARY_FIND(cusparseSetPointerMode)
  CUSPARSE_LIBRARY_FIND(cusparseLoggerSetCallback)
  CUSPARSE_LIBRARY_FIND(cusparseLoggerSetFile)
  CUSPARSE_LIBRARY_FIND(cusparseLoggerOpenFile)
  CUSPARSE_LIBRARY_FIND(cusparseLoggerSetLevel)
  CUSPARSE_LIBRARY_FIND(cusparseLoggerSetMask)
  CUSPARSE_LIBRARY_FIND(cusparseLoggerForceDisable)
  CUSPARSE_LIBRARY_FIND(cusparseCreateMatDescr)
  CUSPARSE_LIBRARY_FIND(cusparseDestroyMatDescr)
  CUSPARSE_LIBRARY_FIND(cusparseCopyMatDescr)
  CUSPARSE_LIBRARY_FIND(cusparseSetMatType)
  CUSPARSE_LIBRARY_FIND(cusparseGetMatType)
  CUSPARSE_LIBRARY_FIND(cusparseSetMatFillMode)
  CUSPARSE_LIBRARY_FIND(cusparseGetMatFillMode)
  CUSPARSE_LIBRARY_FIND(cusparseSetMatDiagType)
  CUSPARSE_LIBRARY_FIND(cusparseGetMatDiagType)
  CUSPARSE_LIBRARY_FIND(cusparseSetMatIndexBase)
  CUSPARSE_LIBRARY_FIND(cusparseGetMatIndexBase)
  CUSPARSE_LIBRARY_FIND(cusparseCreateCsrsv2Info)
  CUSPARSE_LIBRARY_FIND(cusparseDestroyCsrsv2Info)
  CUSPARSE_LIBRARY_FIND(cusparseCreateCsric02Info)
  CUSPARSE_LIBRARY_FIND(cusparseDestroyCsric02Info)
  CUSPARSE_LIBRARY_FIND(cusparseCreateBsric02Info)
  CUSPARSE_LIBRARY_FIND(cusparseDestroyBsric02Info)
  CUSPARSE_LIBRARY_FIND(cusparseCreateCsrilu02Info)
  CUSPARSE_LIBRARY_FIND(cusparseDestroyCsrilu02Info)
  CUSPARSE_LIBRARY_FIND(cusparseCreateBsrilu02Info)
  CUSPARSE_LIBRARY_FIND(cusparseDestroyBsrilu02Info)
  CUSPARSE_LIBRARY_FIND(cusparseCreateBsrsv2Info)
  CUSPARSE_LIBRARY_FIND(cusparseDestroyBsrsv2Info)
  CUSPARSE_LIBRARY_FIND(cusparseCreateBsrsm2Info)
  CUSPARSE_LIBRARY_FIND(cusparseDestroyBsrsm2Info)
  CUSPARSE_LIBRARY_FIND(cusparseCreateCsru2csrInfo)
  CUSPARSE_LIBRARY_FIND(cusparseDestroyCsru2csrInfo)
  CUSPARSE_LIBRARY_FIND(cusparseCreateColorInfo)
  CUSPARSE_LIBRARY_FIND(cusparseDestroyColorInfo)
  CUSPARSE_LIBRARY_FIND(cusparseSetColorAlgs)
  CUSPARSE_LIBRARY_FIND(cusparseGetColorAlgs)
  CUSPARSE_LIBRARY_FIND(cusparseCreatePruneInfo)
  CUSPARSE_LIBRARY_FIND(cusparseDestroyPruneInfo)
  CUSPARSE_LIBRARY_FIND(cusparseSaxpyi)
  CUSPARSE_LIBRARY_FIND(cusparseDaxpyi)
  CUSPARSE_LIBRARY_FIND(cusparseCaxpyi)
  CUSPARSE_LIBRARY_FIND(cusparseZaxpyi)
  CUSPARSE_LIBRARY_FIND(cusparseSgthr)
  CUSPARSE_LIBRARY_FIND(cusparseDgthr)
  CUSPARSE_LIBRARY_FIND(cusparseCgthr)
  CUSPARSE_LIBRARY_FIND(cusparseZgthr)
  CUSPARSE_LIBRARY_FIND(cusparseSgthrz)
  CUSPARSE_LIBRARY_FIND(cusparseDgthrz)
  CUSPARSE_LIBRARY_FIND(cusparseCgthrz)
  CUSPARSE_LIBRARY_FIND(cusparseZgthrz)
  CUSPARSE_LIBRARY_FIND(cusparseSsctr)
  CUSPARSE_LIBRARY_FIND(cusparseDsctr)
  CUSPARSE_LIBRARY_FIND(cusparseCsctr)
  CUSPARSE_LIBRARY_FIND(cusparseZsctr)
  CUSPARSE_LIBRARY_FIND(cusparseSroti)
  CUSPARSE_LIBRARY_FIND(cusparseDroti)
  CUSPARSE_LIBRARY_FIND(cusparseSgemvi)
  CUSPARSE_LIBRARY_FIND(cusparseSgemvi_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseDgemvi)
  CUSPARSE_LIBRARY_FIND(cusparseDgemvi_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseCgemvi)
  CUSPARSE_LIBRARY_FIND(cusparseCgemvi_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseZgemvi)
  CUSPARSE_LIBRARY_FIND(cusparseZgemvi_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseCsrmvEx_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseCsrmvEx)
  CUSPARSE_LIBRARY_FIND(cusparseSbsrmv)
  CUSPARSE_LIBRARY_FIND(cusparseDbsrmv)
  CUSPARSE_LIBRARY_FIND(cusparseCbsrmv)
  CUSPARSE_LIBRARY_FIND(cusparseZbsrmv)
  CUSPARSE_LIBRARY_FIND(cusparseSbsrxmv)
  CUSPARSE_LIBRARY_FIND(cusparseDbsrxmv)
  CUSPARSE_LIBRARY_FIND(cusparseCbsrxmv)
  CUSPARSE_LIBRARY_FIND(cusparseZbsrxmv)
  CUSPARSE_LIBRARY_FIND(cusparseXcsrsv2_zeroPivot)
  CUSPARSE_LIBRARY_FIND(cusparseScsrsv2_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseDcsrsv2_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseCcsrsv2_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseZcsrsv2_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseScsrsv2_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseDcsrsv2_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseCcsrsv2_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseZcsrsv2_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseScsrsv2_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseDcsrsv2_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseCcsrsv2_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseZcsrsv2_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseScsrsv2_solve)
  CUSPARSE_LIBRARY_FIND(cusparseDcsrsv2_solve)
  CUSPARSE_LIBRARY_FIND(cusparseCcsrsv2_solve)
  CUSPARSE_LIBRARY_FIND(cusparseZcsrsv2_solve)
  CUSPARSE_LIBRARY_FIND(cusparseXbsrsv2_zeroPivot)
  CUSPARSE_LIBRARY_FIND(cusparseSbsrsv2_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseDbsrsv2_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseCbsrsv2_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseZbsrsv2_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseSbsrsv2_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseDbsrsv2_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseCbsrsv2_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseZbsrsv2_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseSbsrsv2_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseDbsrsv2_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseCbsrsv2_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseZbsrsv2_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseSbsrsv2_solve)
  CUSPARSE_LIBRARY_FIND(cusparseDbsrsv2_solve)
  CUSPARSE_LIBRARY_FIND(cusparseCbsrsv2_solve)
  CUSPARSE_LIBRARY_FIND(cusparseZbsrsv2_solve)
  CUSPARSE_LIBRARY_FIND(cusparseSbsrmm)
  CUSPARSE_LIBRARY_FIND(cusparseDbsrmm)
  CUSPARSE_LIBRARY_FIND(cusparseCbsrmm)
  CUSPARSE_LIBRARY_FIND(cusparseZbsrmm)
  CUSPARSE_LIBRARY_FIND(cusparseSgemmi)
  CUSPARSE_LIBRARY_FIND(cusparseDgemmi)
  CUSPARSE_LIBRARY_FIND(cusparseCgemmi)
  CUSPARSE_LIBRARY_FIND(cusparseZgemmi)
  CUSPARSE_LIBRARY_FIND(cusparseCreateCsrsm2Info)
  CUSPARSE_LIBRARY_FIND(cusparseDestroyCsrsm2Info)
  CUSPARSE_LIBRARY_FIND(cusparseXcsrsm2_zeroPivot)
  CUSPARSE_LIBRARY_FIND(cusparseScsrsm2_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseDcsrsm2_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseCcsrsm2_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseZcsrsm2_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseScsrsm2_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseDcsrsm2_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseCcsrsm2_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseZcsrsm2_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseScsrsm2_solve)
  CUSPARSE_LIBRARY_FIND(cusparseDcsrsm2_solve)
  CUSPARSE_LIBRARY_FIND(cusparseCcsrsm2_solve)
  CUSPARSE_LIBRARY_FIND(cusparseZcsrsm2_solve)
  CUSPARSE_LIBRARY_FIND(cusparseXbsrsm2_zeroPivot)
  CUSPARSE_LIBRARY_FIND(cusparseSbsrsm2_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseDbsrsm2_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseCbsrsm2_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseZbsrsm2_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseSbsrsm2_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseDbsrsm2_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseCbsrsm2_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseZbsrsm2_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseSbsrsm2_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseDbsrsm2_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseCbsrsm2_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseZbsrsm2_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseSbsrsm2_solve)
  CUSPARSE_LIBRARY_FIND(cusparseDbsrsm2_solve)
  CUSPARSE_LIBRARY_FIND(cusparseCbsrsm2_solve)
  CUSPARSE_LIBRARY_FIND(cusparseZbsrsm2_solve)
  CUSPARSE_LIBRARY_FIND(cusparseScsrilu02_numericBoost)
  CUSPARSE_LIBRARY_FIND(cusparseDcsrilu02_numericBoost)
  CUSPARSE_LIBRARY_FIND(cusparseCcsrilu02_numericBoost)
  CUSPARSE_LIBRARY_FIND(cusparseZcsrilu02_numericBoost)
  CUSPARSE_LIBRARY_FIND(cusparseXcsrilu02_zeroPivot)
  CUSPARSE_LIBRARY_FIND(cusparseScsrilu02_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseDcsrilu02_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseCcsrilu02_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseZcsrilu02_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseScsrilu02_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseDcsrilu02_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseCcsrilu02_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseZcsrilu02_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseScsrilu02_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseDcsrilu02_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseCcsrilu02_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseZcsrilu02_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseScsrilu02)
  CUSPARSE_LIBRARY_FIND(cusparseDcsrilu02)
  CUSPARSE_LIBRARY_FIND(cusparseCcsrilu02)
  CUSPARSE_LIBRARY_FIND(cusparseZcsrilu02)
  CUSPARSE_LIBRARY_FIND(cusparseSbsrilu02_numericBoost)
  CUSPARSE_LIBRARY_FIND(cusparseDbsrilu02_numericBoost)
  CUSPARSE_LIBRARY_FIND(cusparseCbsrilu02_numericBoost)
  CUSPARSE_LIBRARY_FIND(cusparseZbsrilu02_numericBoost)
  CUSPARSE_LIBRARY_FIND(cusparseXbsrilu02_zeroPivot)
  CUSPARSE_LIBRARY_FIND(cusparseSbsrilu02_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseDbsrilu02_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseCbsrilu02_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseZbsrilu02_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseSbsrilu02_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseDbsrilu02_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseCbsrilu02_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseZbsrilu02_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseSbsrilu02_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseDbsrilu02_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseCbsrilu02_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseZbsrilu02_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseSbsrilu02)
  CUSPARSE_LIBRARY_FIND(cusparseDbsrilu02)
  CUSPARSE_LIBRARY_FIND(cusparseCbsrilu02)
  CUSPARSE_LIBRARY_FIND(cusparseZbsrilu02)
  CUSPARSE_LIBRARY_FIND(cusparseXcsric02_zeroPivot)
  CUSPARSE_LIBRARY_FIND(cusparseScsric02_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseDcsric02_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseCcsric02_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseZcsric02_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseScsric02_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseDcsric02_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseCcsric02_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseZcsric02_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseScsric02_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseDcsric02_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseCcsric02_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseZcsric02_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseScsric02)
  CUSPARSE_LIBRARY_FIND(cusparseDcsric02)
  CUSPARSE_LIBRARY_FIND(cusparseCcsric02)
  CUSPARSE_LIBRARY_FIND(cusparseZcsric02)
  CUSPARSE_LIBRARY_FIND(cusparseXbsric02_zeroPivot)
  CUSPARSE_LIBRARY_FIND(cusparseSbsric02_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseDbsric02_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseCbsric02_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseZbsric02_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseSbsric02_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseDbsric02_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseCbsric02_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseZbsric02_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseSbsric02_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseDbsric02_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseCbsric02_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseZbsric02_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseSbsric02)
  CUSPARSE_LIBRARY_FIND(cusparseDbsric02)
  CUSPARSE_LIBRARY_FIND(cusparseCbsric02)
  CUSPARSE_LIBRARY_FIND(cusparseZbsric02)
  CUSPARSE_LIBRARY_FIND(cusparseSgtsv2_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseDgtsv2_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseCgtsv2_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseZgtsv2_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseSgtsv2)
  CUSPARSE_LIBRARY_FIND(cusparseDgtsv2)
  CUSPARSE_LIBRARY_FIND(cusparseCgtsv2)
  CUSPARSE_LIBRARY_FIND(cusparseZgtsv2)
  CUSPARSE_LIBRARY_FIND(cusparseSgtsv2_nopivot_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseDgtsv2_nopivot_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseCgtsv2_nopivot_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseZgtsv2_nopivot_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseSgtsv2_nopivot)
  CUSPARSE_LIBRARY_FIND(cusparseDgtsv2_nopivot)
  CUSPARSE_LIBRARY_FIND(cusparseCgtsv2_nopivot)
  CUSPARSE_LIBRARY_FIND(cusparseZgtsv2_nopivot)
  CUSPARSE_LIBRARY_FIND(cusparseSgtsv2StridedBatch_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseDgtsv2StridedBatch_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseCgtsv2StridedBatch_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseZgtsv2StridedBatch_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseSgtsv2StridedBatch)
  CUSPARSE_LIBRARY_FIND(cusparseDgtsv2StridedBatch)
  CUSPARSE_LIBRARY_FIND(cusparseCgtsv2StridedBatch)
  CUSPARSE_LIBRARY_FIND(cusparseZgtsv2StridedBatch)
  CUSPARSE_LIBRARY_FIND(cusparseSgtsvInterleavedBatch_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseDgtsvInterleavedBatch_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseCgtsvInterleavedBatch_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseZgtsvInterleavedBatch_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseSgtsvInterleavedBatch)
  CUSPARSE_LIBRARY_FIND(cusparseDgtsvInterleavedBatch)
  CUSPARSE_LIBRARY_FIND(cusparseCgtsvInterleavedBatch)
  CUSPARSE_LIBRARY_FIND(cusparseZgtsvInterleavedBatch)
  CUSPARSE_LIBRARY_FIND(cusparseSgpsvInterleavedBatch_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseDgpsvInterleavedBatch_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseCgpsvInterleavedBatch_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseZgpsvInterleavedBatch_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseSgpsvInterleavedBatch)
  CUSPARSE_LIBRARY_FIND(cusparseDgpsvInterleavedBatch)
  CUSPARSE_LIBRARY_FIND(cusparseCgpsvInterleavedBatch)
  CUSPARSE_LIBRARY_FIND(cusparseZgpsvInterleavedBatch)
  CUSPARSE_LIBRARY_FIND(cusparseCreateCsrgemm2Info)
  CUSPARSE_LIBRARY_FIND(cusparseDestroyCsrgemm2Info)
  CUSPARSE_LIBRARY_FIND(cusparseScsrgemm2_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseDcsrgemm2_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseCcsrgemm2_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseZcsrgemm2_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseXcsrgemm2Nnz)
  CUSPARSE_LIBRARY_FIND(cusparseScsrgemm2)
  CUSPARSE_LIBRARY_FIND(cusparseDcsrgemm2)
  CUSPARSE_LIBRARY_FIND(cusparseCcsrgemm2)
  CUSPARSE_LIBRARY_FIND(cusparseZcsrgemm2)
  CUSPARSE_LIBRARY_FIND(cusparseScsrgeam2_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseDcsrgeam2_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseCcsrgeam2_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseZcsrgeam2_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseXcsrgeam2Nnz)
  CUSPARSE_LIBRARY_FIND(cusparseScsrgeam2)
  CUSPARSE_LIBRARY_FIND(cusparseDcsrgeam2)
  CUSPARSE_LIBRARY_FIND(cusparseCcsrgeam2)
  CUSPARSE_LIBRARY_FIND(cusparseZcsrgeam2)
  CUSPARSE_LIBRARY_FIND(cusparseScsrcolor)
  CUSPARSE_LIBRARY_FIND(cusparseDcsrcolor)
  CUSPARSE_LIBRARY_FIND(cusparseCcsrcolor)
  CUSPARSE_LIBRARY_FIND(cusparseZcsrcolor)
  CUSPARSE_LIBRARY_FIND(cusparseSnnz)
  CUSPARSE_LIBRARY_FIND(cusparseDnnz)
  CUSPARSE_LIBRARY_FIND(cusparseCnnz)
  CUSPARSE_LIBRARY_FIND(cusparseZnnz)
  CUSPARSE_LIBRARY_FIND(cusparseSnnz_compress)
  CUSPARSE_LIBRARY_FIND(cusparseDnnz_compress)
  CUSPARSE_LIBRARY_FIND(cusparseCnnz_compress)
  CUSPARSE_LIBRARY_FIND(cusparseZnnz_compress)
  CUSPARSE_LIBRARY_FIND(cusparseScsr2csr_compress)
  CUSPARSE_LIBRARY_FIND(cusparseDcsr2csr_compress)
  CUSPARSE_LIBRARY_FIND(cusparseCcsr2csr_compress)
  CUSPARSE_LIBRARY_FIND(cusparseZcsr2csr_compress)
  CUSPARSE_LIBRARY_FIND(cusparseSdense2csr)
  CUSPARSE_LIBRARY_FIND(cusparseDdense2csr)
  CUSPARSE_LIBRARY_FIND(cusparseCdense2csr)
  CUSPARSE_LIBRARY_FIND(cusparseZdense2csr)
  CUSPARSE_LIBRARY_FIND(cusparseScsr2dense)
  CUSPARSE_LIBRARY_FIND(cusparseDcsr2dense)
  CUSPARSE_LIBRARY_FIND(cusparseCcsr2dense)
  CUSPARSE_LIBRARY_FIND(cusparseZcsr2dense)
  CUSPARSE_LIBRARY_FIND(cusparseSdense2csc)
  CUSPARSE_LIBRARY_FIND(cusparseDdense2csc)
  CUSPARSE_LIBRARY_FIND(cusparseCdense2csc)
  CUSPARSE_LIBRARY_FIND(cusparseZdense2csc)
  CUSPARSE_LIBRARY_FIND(cusparseScsc2dense)
  CUSPARSE_LIBRARY_FIND(cusparseDcsc2dense)
  CUSPARSE_LIBRARY_FIND(cusparseCcsc2dense)
  CUSPARSE_LIBRARY_FIND(cusparseZcsc2dense)
  CUSPARSE_LIBRARY_FIND(cusparseXcoo2csr)
  CUSPARSE_LIBRARY_FIND(cusparseXcsr2coo)
  CUSPARSE_LIBRARY_FIND(cusparseXcsr2bsrNnz)
  CUSPARSE_LIBRARY_FIND(cusparseScsr2bsr)
  CUSPARSE_LIBRARY_FIND(cusparseDcsr2bsr)
  CUSPARSE_LIBRARY_FIND(cusparseCcsr2bsr)
  CUSPARSE_LIBRARY_FIND(cusparseZcsr2bsr)
  CUSPARSE_LIBRARY_FIND(cusparseSbsr2csr)
  CUSPARSE_LIBRARY_FIND(cusparseDbsr2csr)
  CUSPARSE_LIBRARY_FIND(cusparseCbsr2csr)
  CUSPARSE_LIBRARY_FIND(cusparseZbsr2csr)
  CUSPARSE_LIBRARY_FIND(cusparseSgebsr2gebsc_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseDgebsr2gebsc_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseCgebsr2gebsc_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseZgebsr2gebsc_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseSgebsr2gebsc_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseDgebsr2gebsc_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseCgebsr2gebsc_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseZgebsr2gebsc_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseSgebsr2gebsc)
  CUSPARSE_LIBRARY_FIND(cusparseDgebsr2gebsc)
  CUSPARSE_LIBRARY_FIND(cusparseCgebsr2gebsc)
  CUSPARSE_LIBRARY_FIND(cusparseZgebsr2gebsc)
  CUSPARSE_LIBRARY_FIND(cusparseXgebsr2csr)
  CUSPARSE_LIBRARY_FIND(cusparseSgebsr2csr)
  CUSPARSE_LIBRARY_FIND(cusparseDgebsr2csr)
  CUSPARSE_LIBRARY_FIND(cusparseCgebsr2csr)
  CUSPARSE_LIBRARY_FIND(cusparseZgebsr2csr)
  CUSPARSE_LIBRARY_FIND(cusparseScsr2gebsr_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseDcsr2gebsr_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseCcsr2gebsr_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseZcsr2gebsr_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseScsr2gebsr_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseDcsr2gebsr_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseCcsr2gebsr_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseZcsr2gebsr_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseXcsr2gebsrNnz)
  CUSPARSE_LIBRARY_FIND(cusparseScsr2gebsr)
  CUSPARSE_LIBRARY_FIND(cusparseDcsr2gebsr)
  CUSPARSE_LIBRARY_FIND(cusparseCcsr2gebsr)
  CUSPARSE_LIBRARY_FIND(cusparseZcsr2gebsr)
  CUSPARSE_LIBRARY_FIND(cusparseSgebsr2gebsr_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseDgebsr2gebsr_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseCgebsr2gebsr_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseZgebsr2gebsr_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseSgebsr2gebsr_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseDgebsr2gebsr_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseCgebsr2gebsr_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseZgebsr2gebsr_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseXgebsr2gebsrNnz)
  CUSPARSE_LIBRARY_FIND(cusparseSgebsr2gebsr)
  CUSPARSE_LIBRARY_FIND(cusparseDgebsr2gebsr)
  CUSPARSE_LIBRARY_FIND(cusparseCgebsr2gebsr)
  CUSPARSE_LIBRARY_FIND(cusparseZgebsr2gebsr)
  CUSPARSE_LIBRARY_FIND(cusparseCreateIdentityPermutation)
  CUSPARSE_LIBRARY_FIND(cusparseXcoosort_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseXcoosortByRow)
  CUSPARSE_LIBRARY_FIND(cusparseXcoosortByColumn)
  CUSPARSE_LIBRARY_FIND(cusparseXcsrsort_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseXcsrsort)
  CUSPARSE_LIBRARY_FIND(cusparseXcscsort_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseXcscsort)
  CUSPARSE_LIBRARY_FIND(cusparseScsru2csr_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseDcsru2csr_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseCcsru2csr_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseZcsru2csr_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseScsru2csr)
  CUSPARSE_LIBRARY_FIND(cusparseDcsru2csr)
  CUSPARSE_LIBRARY_FIND(cusparseCcsru2csr)
  CUSPARSE_LIBRARY_FIND(cusparseZcsru2csr)
  CUSPARSE_LIBRARY_FIND(cusparseScsr2csru)
  CUSPARSE_LIBRARY_FIND(cusparseDcsr2csru)
  CUSPARSE_LIBRARY_FIND(cusparseCcsr2csru)
  CUSPARSE_LIBRARY_FIND(cusparseZcsr2csru)
  CUSPARSE_LIBRARY_FIND(cusparseSpruneDense2csr_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseDpruneDense2csr_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseSpruneDense2csrNnz)
  CUSPARSE_LIBRARY_FIND(cusparseDpruneDense2csrNnz)
  CUSPARSE_LIBRARY_FIND(cusparseSpruneDense2csr)
  CUSPARSE_LIBRARY_FIND(cusparseDpruneDense2csr)
  CUSPARSE_LIBRARY_FIND(cusparseSpruneCsr2csr_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseDpruneCsr2csr_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseSpruneCsr2csrNnz)
  CUSPARSE_LIBRARY_FIND(cusparseDpruneCsr2csrNnz)
  CUSPARSE_LIBRARY_FIND(cusparseSpruneCsr2csr)
  CUSPARSE_LIBRARY_FIND(cusparseDpruneCsr2csr)
  CUSPARSE_LIBRARY_FIND(cusparseSpruneDense2csrByPercentage_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseDpruneDense2csrByPercentage_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseSpruneDense2csrNnzByPercentage)
  CUSPARSE_LIBRARY_FIND(cusparseDpruneDense2csrNnzByPercentage)
  CUSPARSE_LIBRARY_FIND(cusparseSpruneDense2csrByPercentage)
  CUSPARSE_LIBRARY_FIND(cusparseDpruneDense2csrByPercentage)
  CUSPARSE_LIBRARY_FIND(cusparseSpruneCsr2csrByPercentage_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseDpruneCsr2csrByPercentage_bufferSizeExt)
  CUSPARSE_LIBRARY_FIND(cusparseSpruneCsr2csrNnzByPercentage)
  CUSPARSE_LIBRARY_FIND(cusparseDpruneCsr2csrNnzByPercentage)
  CUSPARSE_LIBRARY_FIND(cusparseSpruneCsr2csrByPercentage)
  CUSPARSE_LIBRARY_FIND(cusparseDpruneCsr2csrByPercentage)
  CUSPARSE_LIBRARY_FIND(cusparseCsr2cscEx2)
  CUSPARSE_LIBRARY_FIND(cusparseCsr2cscEx2_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseCreateSpVec)
  CUSPARSE_LIBRARY_FIND(cusparseDestroySpVec)
  CUSPARSE_LIBRARY_FIND(cusparseSpVecGet)
  CUSPARSE_LIBRARY_FIND(cusparseSpVecGetIndexBase)
  CUSPARSE_LIBRARY_FIND(cusparseSpVecGetValues)
  CUSPARSE_LIBRARY_FIND(cusparseSpVecSetValues)
  CUSPARSE_LIBRARY_FIND(cusparseCreateDnVec)
  CUSPARSE_LIBRARY_FIND(cusparseDestroyDnVec)
  CUSPARSE_LIBRARY_FIND(cusparseDnVecGet)
  CUSPARSE_LIBRARY_FIND(cusparseDnVecGetValues)
  CUSPARSE_LIBRARY_FIND(cusparseDnVecSetValues)
  CUSPARSE_LIBRARY_FIND(cusparseDestroySpMat)
  CUSPARSE_LIBRARY_FIND(cusparseSpMatGetFormat)
  CUSPARSE_LIBRARY_FIND(cusparseSpMatGetIndexBase)
  CUSPARSE_LIBRARY_FIND(cusparseSpMatGetValues)
  CUSPARSE_LIBRARY_FIND(cusparseSpMatSetValues)
  CUSPARSE_LIBRARY_FIND(cusparseSpMatGetSize)
  CUSPARSE_LIBRARY_FIND(cusparseSpMatSetStridedBatch)
  CUSPARSE_LIBRARY_FIND(cusparseSpMatGetStridedBatch)
  CUSPARSE_LIBRARY_FIND(cusparseCooSetStridedBatch)
  CUSPARSE_LIBRARY_FIND(cusparseCsrSetStridedBatch)
  CUSPARSE_LIBRARY_FIND(cusparseSpMatGetAttribute)
  CUSPARSE_LIBRARY_FIND(cusparseSpMatSetAttribute)
  CUSPARSE_LIBRARY_FIND(cusparseCreateCsr)
  CUSPARSE_LIBRARY_FIND(cusparseCreateCsc)
  CUSPARSE_LIBRARY_FIND(cusparseCsrGet)
  CUSPARSE_LIBRARY_FIND(cusparseCsrSetPointers)
  CUSPARSE_LIBRARY_FIND(cusparseCscSetPointers)
  CUSPARSE_LIBRARY_FIND(cusparseCreateCoo)
  CUSPARSE_LIBRARY_FIND(cusparseCreateCooAoS)
  CUSPARSE_LIBRARY_FIND(cusparseCooGet)
  CUSPARSE_LIBRARY_FIND(cusparseCooAoSGet)
  CUSPARSE_LIBRARY_FIND(cusparseCooSetPointers)
  CUSPARSE_LIBRARY_FIND(cusparseCreateBlockedEll)
  CUSPARSE_LIBRARY_FIND(cusparseBlockedEllGet)
  CUSPARSE_LIBRARY_FIND(cusparseCreateDnMat)
  CUSPARSE_LIBRARY_FIND(cusparseDestroyDnMat)
  CUSPARSE_LIBRARY_FIND(cusparseDnMatGet)
  CUSPARSE_LIBRARY_FIND(cusparseDnMatGetValues)
  CUSPARSE_LIBRARY_FIND(cusparseDnMatSetValues)
  CUSPARSE_LIBRARY_FIND(cusparseDnMatSetStridedBatch)
  CUSPARSE_LIBRARY_FIND(cusparseDnMatGetStridedBatch)
  CUSPARSE_LIBRARY_FIND(cusparseAxpby)
  CUSPARSE_LIBRARY_FIND(cusparseGather)
  CUSPARSE_LIBRARY_FIND(cusparseScatter)
  CUSPARSE_LIBRARY_FIND(cusparseRot)
  CUSPARSE_LIBRARY_FIND(cusparseSpVV_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseSpVV)
  CUSPARSE_LIBRARY_FIND(cusparseSparseToDense_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseSparseToDense)
  CUSPARSE_LIBRARY_FIND(cusparseDenseToSparse_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseDenseToSparse_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseDenseToSparse_convert)
  CUSPARSE_LIBRARY_FIND(cusparseSpMV)
  CUSPARSE_LIBRARY_FIND(cusparseSpMV_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseSpSV_createDescr)
  CUSPARSE_LIBRARY_FIND(cusparseSpSV_destroyDescr)
  CUSPARSE_LIBRARY_FIND(cusparseSpSV_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseSpSV_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseSpSV_solve)
  CUSPARSE_LIBRARY_FIND(cusparseSpSM_createDescr)
  CUSPARSE_LIBRARY_FIND(cusparseSpSM_destroyDescr)
  CUSPARSE_LIBRARY_FIND(cusparseSpSM_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseSpSM_analysis)
  CUSPARSE_LIBRARY_FIND(cusparseSpSM_solve)
  CUSPARSE_LIBRARY_FIND(cusparseSpMM_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseSpMM_preprocess)
  CUSPARSE_LIBRARY_FIND(cusparseSpMM)
  CUSPARSE_LIBRARY_FIND(cusparseSpGEMM_createDescr)
  CUSPARSE_LIBRARY_FIND(cusparseSpGEMM_destroyDescr)
  CUSPARSE_LIBRARY_FIND(cusparseSpGEMM_workEstimation)
  CUSPARSE_LIBRARY_FIND(cusparseSpGEMM_compute)
  CUSPARSE_LIBRARY_FIND(cusparseSpGEMM_copy)
  CUSPARSE_LIBRARY_FIND(cusparseSpGEMMreuse_workEstimation)
  CUSPARSE_LIBRARY_FIND(cusparseSpGEMMreuse_nnz)
  CUSPARSE_LIBRARY_FIND(cusparseSpGEMMreuse_copy)
  CUSPARSE_LIBRARY_FIND(cusparseSpGEMMreuse_compute)
  CUSPARSE_LIBRARY_FIND(cusparseConstrainedGeMM)
  CUSPARSE_LIBRARY_FIND(cusparseConstrainedGeMM_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseSDDMM_bufferSize)
  CUSPARSE_LIBRARY_FIND(cusparseSDDMM_preprocess)
  CUSPARSE_LIBRARY_FIND(cusparseSDDMM)
  CUSPARSE_LIBRARY_FIND(cusparseSpMMOp_createPlan)
  CUSPARSE_LIBRARY_FIND(cusparseSpMMOp)
  CUSPARSE_LIBRARY_FIND(cusparseSpMMOp_destroyPlan)
  result = 0; // success
  return result;
}
